package:
  name: modloader
  version: 0.0.1
  
source:
    path: .

build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False
  include_recipe: False

about:
  home: http://modloader64.com
  license: GPL-3
  summary: ModLoader core library