set(WAMR_ROOT_DIR "${MODLOADER_ROOT}/third_party/wamr")
string(TOLOWER ${CMAKE_SYSTEM_NAME} WAMR_BUILD_PLATFORM)
set(WAMR_BUILD_TARGET "X86_64")
foreach(feature INTERP AOT MEMORY64 SHARED_HEAP BULK_MEMORY REF_TYPES SHARED_MEMORY THREAD_MGR)
    set(WAMR_BUILD_${feature} 1)
endforeach()
foreach(feature FAST_INTERP JIT LIBC_BUILTIN LIBC_WASI SIMD MULTI_MODULE LIB_PTHREAD)
    set(WAMR_BUILD_${feature} 0)
endforeach()
add_compile_definitions(WASM_ENABLE_HEAP_AUX_STACK_ALLOCATION=1)
add_compile_definitions(WASM_RUNTIME_API_EXTERN= WASM_API_EXTERN=)
if(WIN32)
    if(NOT CMAKE_ASM_MASM_COMPILER)
        get_filename_component(compiler_directory "${CMAKE_C_COMPILER}" DIRECTORY)
        find_program(modloader_masm NAMES ml64 llvm-ml HINTS "${compiler_directory}" REQUIRED)
        set(CMAKE_ASM_MASM_COMPILER "${modloader_masm}" CACHE FILEPATH "MASM-compatible assembler" FORCE)
    endif()
    if(CMAKE_ASM_MASM_COMPILER MATCHES "llvm-ml")
        set(CMAKE_ASM_MASM_FLAGS "--m64" CACHE STRING "Assembler flags" FORCE)
    endif()
endif()
include(${WAMR_ROOT_DIR}/build-scripts/runtime_lib.cmake)
if(WIN32)
    set(CMAKE_ASM_MASM_COMPILE_OBJECT
        "\"<CMAKE_ASM_MASM_COMPILER>\" <FLAGS> /nologo /c /Fo\"<OBJECT>\" \"<SOURCE>\"")
endif()
configure_file(${WAMR_ROOT_DIR}/core/version.h.in ${WAMR_ROOT_DIR}/core/version.h @ONLY NEWLINE_STYLE UNIX)
add_library(vmlib STATIC ${WAMR_RUNTIME_LIB_SOURCE})
if (WIN32)
    target_compile_definitions(vmlib PRIVATE COMPILING_WASM_RUNTIME_API=1)
    target_link_libraries(vmlib PUBLIC ws2_32 ntdll)
endif ()

set(SDL_STATIC ON)
set(SDL_SHARED OFF)
set(SDL_TEST_LIBRARY OFF)
set(SDL_EXAMPLES OFF)
add_subdirectory(${MODLOADER_ROOT}/third_party/sdl ${CMAKE_CURRENT_BINARY_DIR}/sdl EXCLUDE_FROM_ALL)

set(ZLIB_ROOT_DIR ${MODLOADER_ROOT}/third_party/zlib)
set(ZLIB_BUILD_SHARED OFF)
set(ZLIB_BUILD_STATIC ON)
set(ZLIB_BUILD_TESTING OFF)
set(ZLIB_INSTALL OFF)
add_subdirectory(${ZLIB_ROOT_DIR} ${CMAKE_CURRENT_BINARY_DIR}/zlib EXCLUDE_FROM_ALL)

add_library(modloader_zip STATIC
    ${ZLIB_ROOT_DIR}/contrib/minizip/unzip.c
    ${ZLIB_ROOT_DIR}/contrib/minizip/ioapi.c)
target_include_directories(modloader_zip PUBLIC ${ZLIB_ROOT_DIR}/contrib/minizip)
target_link_libraries(modloader_zip PUBLIC ZLIB::ZLIBSTATIC)
target_compile_definitions(modloader_zip PRIVATE NOUNCRYPT)

add_library(modloader_yyjson STATIC ${MODLOADER_ROOT}/third_party/yyjson/src/yyjson.c)
target_include_directories(modloader_yyjson PUBLIC ${MODLOADER_ROOT}/third_party/yyjson/src)

set(MONOCYPHER_ROOT_DIR ${MODLOADER_ROOT}/third_party/monocypher)
add_library(modloader_monocypher STATIC ${MONOCYPHER_ROOT_DIR}/src/monocypher.c)
target_include_directories(modloader_monocypher PUBLIC ${MONOCYPHER_ROOT_DIR}/src)

set(BUILD_SHARED_LIBS OFF)
foreach(dependency ZLIB BZIP2 PNG HARFBUZZ BROTLI)
    set(FT_DISABLE_${dependency} ON)
endforeach()
add_subdirectory(${MODLOADER_ROOT}/third_party/freetype ${CMAKE_CURRENT_BINARY_DIR}/freetype EXCLUDE_FROM_ALL)
add_library(Freetype::Freetype ALIAS freetype)

set(IMGUI_ROOT_DIR ${MODLOADER_ROOT}/third_party/imgui)
file(GLOB imgui_sources CONFIGURE_DEPENDS ${IMGUI_ROOT_DIR}/*.cpp)
add_library(modloader_imgui STATIC ${imgui_sources}
    ${IMGUI_ROOT_DIR}/backends/imgui_impl_sdl3.cpp
    ${IMGUI_ROOT_DIR}/misc/freetype/imgui_freetype.cpp
)
target_include_directories(modloader_imgui PUBLIC ${IMGUI_ROOT_DIR})
target_compile_definitions(modloader_imgui PUBLIC IMGUI_USER_CONFIG="modloader_imgui_config.h" PRIVATE IMGUI_ENABLE_FREETYPE)
target_link_libraries(modloader_imgui PUBLIC ModLoader::ABI SDL3::SDL3-static PRIVATE Freetype::Freetype)

set(CMAKE_DISABLE_FIND_PACKAGE_Freetype ON)
set(RMLUI_SAMPLES OFF)
set(RMLUI_TESTS OFF)
set(RMLUI_LUA_BINDINGS OFF)
add_subdirectory(${MODLOADER_ROOT}/third_party/rmlui ${CMAKE_CURRENT_BINARY_DIR}/rmlui EXCLUDE_FROM_ALL)
