#!/usr/bin/env python3
import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parent / "shaders.h"
SHADERS = [
    ("Ui_Vertex", "ui.hlsl", "Vertex_Main", "vs"),
    ("Ui_Pixel", "ui.hlsl", "Pixel_Main", "ps"),
    ("Image_Vertex", "image.hlsl", "Vertex_Main", "vs"),
    ("Image_Pixel", "image.hlsl", "Pixel_Main", "ps"),
]


def find(name, candidates):
    found = shutil.which(name)
    if found:
        return found
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)
    sys.exit(f"cannot find {name}; pass --{name}")


def vulkan_sdk_tool(name):
    sdk = os.environ.get("VULKAN_SDK")
    return [Path(sdk) / "Bin" / f"{name}.exe", Path(sdk) / "bin" / name] if sdk else []


def compile_shader(command):
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"{' '.join(command)}\n{result.stdout}{result.stderr}")


def array(name, data):
    lines = [f"alignas(u32) constexpr u8 {name}[] = {{"]
    for start in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in data[start:start + 24]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Compiles the renderer's shaders into shaders.h")
    parser.add_argument("--dxc")
    arguments = parser.parse_args()
    dxc = arguments.dxc or find("dxc", vulkan_sdk_tool("dxc"))

    parts = ["// Generated by shaders/build_shaders.py", "#pragma once", "", '#include "base.h"', ""]
    with tempfile.TemporaryDirectory() as directory:
        for name, source, entry, stage in SHADERS:
            spirv = Path(directory) / f"{name}.spv"
            compile_shader([dxc, "-nologo", "-O3", "-spirv", "-fspv-target-env=vulkan1.1", "-T", f"{stage}_6_0", "-E", entry, "-Fo", str(spirv), str(HERE / source)])
            parts.append(array(f"g{name}_Spirv", spirv.read_bytes()))
            parts.append("")
    OUTPUT.write_text("\n".join(parts), newline="\n")
    print(f"{OUTPUT}: {len(SHADERS)} shaders")


if __name__ == "__main__":
    main()
