//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.Core {
    
    
    public class PluginDelegates : IPluginDelegates {
        
        public Init_Delegate Init { get; set; }//;
        
        public Destroy_Delegate Destroy { get; set; }//;
        
        public PluginDelegates(System.Type binding) {
            Init = DelegateHelper.Cast<Init_Delegate>(DelegateHelper.CreateDelegate(binding.GetMethod("Init", new Type[] {})!, null));
            Destroy = DelegateHelper.Cast<Destroy_Delegate>(DelegateHelper.CreateDelegate(binding.GetMethod("Destroy", new Type[] {})!, null));
        }
    }
}
