//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.API {
    
    
    public delegate void InitBinding_Delegate();
    
    public delegate void StartBinding_Delegate();
    
    public delegate void StopBinding_Delegate();
    
    public delegate void SetGameFile_Delegate(string file);
    
    public delegate bool ChangeGameFile_Delegate(string file);
    
    public delegate void TogglePause_Delegate();
    
    public delegate bool SaveState_Delegate(string file);
    
    public delegate bool LoadState_Delegate(string file);
    
    public interface IBindingDelegates {
        
        public InitBinding_Delegate InitBinding {get; set;}
        public StartBinding_Delegate StartBinding {get; set;}
        public StopBinding_Delegate StopBinding {get; set;}
        public SetGameFile_Delegate SetGameFile {get; set;}
        public ChangeGameFile_Delegate ChangeGameFile {get; set;}
        public TogglePause_Delegate TogglePause {get; set;}
        public SaveState_Delegate SaveState {get; set;}
        public LoadState_Delegate LoadState {get; set;}
    }
}
