//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.API {
    
    
    public delegate byte ReadU8_Delegate(uint address);
    
    public delegate ushort ReadU16_Delegate(uint address);
    
    public delegate uint ReadU32_Delegate(uint address);
    
    public delegate ulong ReadU64_Delegate(uint address);
    
    public delegate sbyte ReadS8_Delegate(uint address);
    
    public delegate short ReadS16_Delegate(uint address);
    
    public delegate int ReadS32_Delegate(uint address);
    
    public delegate long ReadS64_Delegate(uint address);
    
    public delegate float ReadF32_Delegate(uint address);
    
    public delegate double ReadF64_Delegate(uint address);
    
    public delegate void WriteU8_Delegate(uint address, byte value);
    
    public delegate void WriteU16_Delegate(uint address, ushort value);
    
    public delegate void WriteU32_Delegate(uint address, uint value);
    
    public delegate void WriteU64_Delegate(uint address, ulong value);
    
    public delegate void WriteS8_Delegate(uint address, sbyte value);
    
    public delegate void WriteS16_Delegate(uint address, short value);
    
    public delegate void WriteS32_Delegate(uint address, int value);
    
    public delegate void WriteS64_Delegate(uint address, long value);
    
    public delegate void WriteF32_Delegate(uint address, float value);
    
    public delegate void WriteF64_Delegate(uint address, double value);
    
    public interface IMemoryDelegates {
        
        public ReadU8_Delegate ReadU8 {get; set;}
        public ReadU16_Delegate ReadU16 {get; set;}
        public ReadU32_Delegate ReadU32 {get; set;}
        public ReadU64_Delegate ReadU64 {get; set;}
        public ReadS8_Delegate ReadS8 {get; set;}
        public ReadS16_Delegate ReadS16 {get; set;}
        public ReadS32_Delegate ReadS32 {get; set;}
        public ReadS64_Delegate ReadS64 {get; set;}
        public ReadF32_Delegate ReadF32 {get; set;}
        public ReadF64_Delegate ReadF64 {get; set;}
        public WriteU8_Delegate WriteU8 {get; set;}
        public WriteU16_Delegate WriteU16 {get; set;}
        public WriteU32_Delegate WriteU32 {get; set;}
        public WriteU64_Delegate WriteU64 {get; set;}
        public WriteS8_Delegate WriteS8 {get; set;}
        public WriteS16_Delegate WriteS16 {get; set;}
        public WriteS32_Delegate WriteS32 {get; set;}
        public WriteS64_Delegate WriteS64 {get; set;}
        public WriteF32_Delegate WriteF32 {get; set;}
        public WriteF64_Delegate WriteF64 {get; set;}
    }
}
