include_guard(GLOBAL)

function(_modloader_lifecycle_callbacks output definition)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${definition}")
    file(STRINGS "${definition}" rows)
    set(callbacks)
    foreach(row IN LISTS rows)
        if(row MATCHES "^MODLOADER_LIFECYCLE\\([^,]+, \\([^)]*\\), ([^, ]+), ([^, ]+), ([^, ]+), [^)]+\\)$")
            list(APPEND callbacks "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}" "${CMAKE_MATCH_3}")
        endif()
    endforeach()
    set(${output} "${callbacks}" PARENT_SCOPE)
endfunction()

function(_modloader_component name folder)
    string(SHA256 component_hash "${name}")
    string(SUBSTRING "${component_hash}" 0 16 component_hash)
    set(prefix "ModLoader_Component_${component_hash}")
    _modloader_lifecycle_callbacks(callbacks "${MODLOADER_SDK_DIR}/include/modloader/detail/lifecycle.def")
    list(APPEND callbacks On_Prepare)
    set(platform_include)
    set(platform_lifecycle_include)
    set(platform_definition)
    set(platform_pointer nullptr)
    if(MODLOADER_PLATFORM_LIFECYCLE)
        _modloader_lifecycle_callbacks(platform_callbacks "${MODLOADER_SDK_DIR}/include/${MODLOADER_PLATFORM_LIFECYCLE}")
        list(APPEND callbacks ${platform_callbacks})
        set(platform_include "#include <${MODLOADER_PLATFORM_COMPONENT_HEADER}>")
        set(platform_lifecycle_include "#include <${MODLOADER_PLATFORM_LIFECYCLE}>")
        set(platform_definition "constexpr ${MODLOADER_PLATFORM_COMPONENT_TYPE} gPlatformCallbacks{\n#define MODLOADER_LIFECYCLE(field, arguments, pre, normal, post, event) .field = {pre, normal, post},\n${platform_lifecycle_include}\n#undef MODLOADER_LIFECYCLE\n};")
        set(platform_pointer "&gPlatformCallbacks")
    endif()
    foreach(callback IN LISTS callbacks)
        target_compile_definitions(${name} PRIVATE "${callback}=${prefix}_${callback}")
    endforeach()
    target_compile_definitions(${name} PRIVATE
        "MODLOADER_LIBRARY_FOLDER=\"${folder}\""
        "MODLOADER_MODULE_NAME=\"${name}\"")
    set(source "${CMAKE_CURRENT_BINARY_DIR}/${name}_component.cpp")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/component.cpp.in" "${source}" @ONLY)
    target_sources(${name} PRIVATE "${source}")
endfunction()
