include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/sdk.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/package.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/lifecycle.cmake")

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Debug, Release, RelWithDebInfo or MinSizeRel" FORCE)
endif()
_modloader_load_runtime()

function(modloader_add_module name)
    cmake_parse_arguments(ARG "" "MANIFEST;ASSETS" "SOURCES;INCLUDE;LIBRARIES" ${ARGN})
    if(ARG_ASSETS)
        cmake_path(ABSOLUTE_PATH ARG_ASSETS BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE)
    endif()
    cmake_path(ABSOLUTE_PATH ARG_MANIFEST BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_MANIFEST}")
    file(READ "${ARG_MANIFEST}" manifest)
    string(JSON count LENGTH "${manifest}" dependencies)
    set(dependencies)
    set(index 0)
    while(index LESS count)
        string(JSON dependency GET "${manifest}" dependencies ${index})
        list(APPEND dependencies "${dependency}")
        math(EXPR index "${index} + 1")
    endwhile()
    string(JSON folder ERROR_VARIABLE missing GET "${manifest}" folder)
    if(missing OR folder STREQUAL "")
        set(folder "${name}")
    endif()
    file(GLOB module_sources CONFIGURE_DEPENDS "${MODLOADER_SDK_DIR}/module/*.cpp")
    add_library(${name} STATIC ${ARG_SOURCES} ${module_sources})
    set_target_properties(${name} PROPERTIES
        MODLOADER_MODULE_FOLDER "${folder}"
        MODLOADER_MODULE_DEPENDENCIES "${dependencies}"
        MODLOADER_MODULE_MANIFEST "${ARG_MANIFEST}"
        MODLOADER_MODULE_MANIFEST_JSON "${manifest}")
    _modloader_stage_assets(${name} "${ARG_ASSETS}")
    target_compile_options(${name} PRIVATE -fvisibility=hidden)
    add_library(${name}_api INTERFACE)
    target_include_directories(${name}_api INTERFACE ${ARG_INCLUDE})
    target_link_libraries(${name}_api INTERFACE modloader_runtime)
    target_link_libraries(${name} PRIVATE ${name}_api ${ARG_LIBRARIES})
    foreach(dependency IN LISTS dependencies)
        add_dependencies(${name} ${dependency})
        target_link_libraries(${name}_api INTERFACE ${dependency}_api)
    endforeach()
    _modloader_component(${name} "${folder}")
    _modloader_package(${name} "${ARG_LIBRARIES}")
endfunction()

function(modloader_import_module name)
    cmake_parse_arguments(ARG "" "WASM;PACKAGE;ASSETS;NAMESPACE" "INCLUDE;DEPENDENCIES" ${ARGN})
    cmake_path(ABSOLUTE_PATH ARG_WASM NORMALIZE)
    set(output "${CMAKE_BINARY_DIR}/modules/${name}.wasm")
    add_custom_command(OUTPUT "${output}"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_BINARY_DIR}/modules"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${ARG_WASM}" "${output}"
        DEPENDS "${ARG_WASM}" VERBATIM)
    add_custom_target(${name} DEPENDS "${output}")
    add_dependencies(${name} modloader_runtime_package)
    set_target_properties(${name} PROPERTIES
        MODLOADER_MODULE_FILE "${output}"
        MODLOADER_MODULE_DEPENDENCIES "${ARG_DEPENDENCIES}"
        MODLOADER_MODULE_NAMESPACE "${ARG_NAMESPACE}")
    if(ARG_ASSETS)
        cmake_path(ABSOLUTE_PATH ARG_ASSETS NORMALIZE)
        _modloader_stage_assets(${name} "${ARG_ASSETS}")
    endif()
    if(ARG_PACKAGE)
        cmake_path(ABSOLUTE_PATH ARG_PACKAGE NORMALIZE)
        set_property(TARGET ${name} PROPERTY MODLOADER_MODULE_PACKAGE "${ARG_PACKAGE}")
    endif()
    add_library(${name}_api INTERFACE IMPORTED GLOBAL)
    target_include_directories(${name}_api INTERFACE ${ARG_INCLUDE})
    target_link_libraries(${name}_api INTERFACE ModLoader::Runtime)
    add_dependencies(${name}_api ${name})
    foreach(dependency IN LISTS ARG_DEPENDENCIES)
        target_link_libraries(${name}_api INTERFACE ${dependency}_api)
        add_dependencies(${name} ${dependency})
    endforeach()
    if(ARG_NAMESPACE)
        add_library(${ARG_NAMESPACE}API ALIAS ${name}_api)
    endif()
endfunction()

function(_modloader_install_development name destination namespace)
    get_property(exported GLOBAL PROPERTY MODLOADER_EXPORTED_MODULES)
    if(name IN_LIST exported)
        return()
    endif()
    if(NOT namespace)
        get_target_property(existing_namespace ${name} MODLOADER_MODULE_NAMESPACE)
        if(existing_namespace)
            set(namespace "${existing_namespace}")
        endif()
    endif()
    set_property(TARGET ${name} PROPERTY MODLOADER_MODULE_NAMESPACE "${namespace}")
    set_property(GLOBAL APPEND PROPERTY MODLOADER_EXPORTED_MODULES "${name}")
    get_target_property(manifest ${name} MODLOADER_MODULE_MANIFEST)
    get_target_property(package ${name} MODLOADER_MODULE_PACKAGE)
    set(module_package)
    if(manifest OR package)
        set(module_package "PACKAGE \"\${_modloader_${name}_prefix}/${destination}/${name}.pak\"")
    endif()
    get_target_property(assets ${name} MODLOADER_MODULE_ASSETS)
    set(module_assets)
    if(assets)
        set(module_assets "ASSETS \"\${_modloader_${name}_prefix}/${destination}/${name}.assets\"")
    endif()
    get_target_property(dependencies ${name} MODLOADER_MODULE_DEPENDENCIES)
    get_target_property(include_directories ${name}_api INTERFACE_INCLUDE_DIRECTORIES)
    set(dependency_find)
    foreach(dependency IN LISTS dependencies)
        string(APPEND dependency_find "find_dependency(${dependency} CONFIG REQUIRED)\n")
    endforeach()
    set(module_dependencies)
    if(dependencies)
        list(JOIN dependencies " " dependency_arguments)
        set(module_dependencies "DEPENDENCIES ${dependency_arguments}")
    endif()
    set(module_namespace)
    if(namespace)
        set(module_namespace "NAMESPACE \"${namespace}\"")
    endif()
    set(module_include)
    if(include_directories)
        foreach(directory IN LISTS include_directories)
            install(DIRECTORY "${directory}/" DESTINATION "include/${name}")
        endforeach()
        set(module_include "INCLUDE \"\${_modloader_${name}_prefix}/include/${name}\"")
    endif()
    set(configuration "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/modloader/${name}Config.cmake")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/module-config.cmake.in" "${configuration}" @ONLY)
    install(FILES "${configuration}" DESTINATION "lib/cmake/${name}")
endfunction()

function(modloader_install_module name)
    cmake_parse_arguments(ARG "DEVELOPMENT" "DESTINATION;NAMESPACE" "" ${ARGN})
    if(NOT ARG_DESTINATION)
        set(ARG_DESTINATION plugins)
    endif()
    get_property(installed GLOBAL PROPERTY MODLOADER_INSTALLED_MODULES)
    set(key "${ARG_DESTINATION}/${name}/${ARG_DEVELOPMENT}")
    if(key IN_LIST installed)
        return()
    endif()
    set_property(GLOBAL APPEND PROPERTY MODLOADER_INSTALLED_MODULES "${key}")
    get_target_property(module_file ${name} MODLOADER_MODULE_FILE)
    set(development)
    if(ARG_DEVELOPMENT)
        set(development DEVELOPMENT)
        _modloader_install_development(${name} "${ARG_DESTINATION}" "${ARG_NAMESPACE}")
    endif()
    get_target_property(manifest ${name} MODLOADER_MODULE_MANIFEST)
    get_target_property(package ${name} MODLOADER_MODULE_PACKAGE)
    if(manifest OR package)
        _modloader_create_package(${name})
        get_target_property(package ${name} MODLOADER_MODULE_PACKAGE)
        set_property(TARGET ${name}_package PROPERTY EXCLUDE_FROM_ALL FALSE)
        install(FILES "${package}" DESTINATION "${ARG_DESTINATION}" RENAME "${name}.pak")
    endif()
    if(ARG_DEVELOPMENT OR (NOT manifest AND NOT package))
        install(FILES "${module_file}" DESTINATION "${ARG_DESTINATION}")
        get_target_property(assets ${name} MODLOADER_MODULE_ASSETS)
        if(assets)
            install(DIRECTORY "${assets}/" DESTINATION "${ARG_DESTINATION}/${name}.assets")
        endif()
    endif()
    get_target_property(dependencies ${name} MODLOADER_MODULE_DEPENDENCIES)
    foreach(dependency IN LISTS dependencies)
        modloader_install_module(${dependency} ${development} DESTINATION "${ARG_DESTINATION}")
    endforeach()
    get_property(destinations GLOBAL PROPERTY MODLOADER_INSTALLED_RUNTIMES)
    if(NOT ARG_DESTINATION IN_LIST destinations)
        set_property(GLOBAL APPEND PROPERTY MODLOADER_INSTALLED_RUNTIMES "${ARG_DESTINATION}")
        install(FILES "${CMAKE_BINARY_DIR}/modules/${MODLOADER_RUNTIME_NAME}" DESTINATION "${ARG_DESTINATION}")
    endif()
endfunction()
