include_guard(GLOBAL)

if(CMAKE_HOST_WIN32 AND MODLOADER_NATIVE_CLANG_CL)
    set(c_names clang-cl)
    set(cxx_names clang-cl)
else()
    set(c_names clang)
    set(cxx_names clang++)
endif()
if(NOT DEFINED CMAKE_C_COMPILER AND "$ENV{CC}" STREQUAL "")
    find_program(CMAKE_C_COMPILER NAMES ${c_names} REQUIRED)
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER AND "$ENV{CXX}" STREQUAL "")
    find_program(CMAKE_CXX_COMPILER NAMES ${cxx_names} REQUIRED)
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build configuration")
endif()
