// Generated by client/src/ui/generate_imgui_bindings.py
#include "imgui_bindings.h"

namespace Imgui = ModLoader::Runtime::Imgui;

extern "C" {

IMGUI_IMPORT("ImGui_ShowDemoWindow") void ImGui_ShowDemoWindow(bool* p_open);
IMGUI_IMPORT("ImGui_ShowMetricsWindow") void ImGui_ShowMetricsWindow(bool* p_open);
IMGUI_IMPORT("ImGui_ShowDebugLogWindow") void ImGui_ShowDebugLogWindow(bool* p_open);
IMGUI_IMPORT("ImGui_ShowIDStackToolWindow") void ImGui_ShowIDStackToolWindow(bool* p_open);
IMGUI_IMPORT("ImGui_ShowAboutWindow") void ImGui_ShowAboutWindow(bool* p_open);
IMGUI_IMPORT("ImGui_ShowStyleEditor") void ImGui_ShowStyleEditor();
IMGUI_IMPORT("ImGui_ShowStyleSelector") bool ImGui_ShowStyleSelector(const char* label);
IMGUI_IMPORT("ImGui_ShowFontSelector") void ImGui_ShowFontSelector(const char* label);
IMGUI_IMPORT("ImGui_ShowUserGuide") void ImGui_ShowUserGuide();
IMGUI_IMPORT("ImGui_GetVersion") u64 ImGui_GetVersion(char* buffer, u64 capacity);
IMGUI_IMPORT("ImGui_StyleColorsDark") void ImGui_StyleColorsDark();
IMGUI_IMPORT("ImGui_StyleColorsLight") void ImGui_StyleColorsLight();
IMGUI_IMPORT("ImGui_StyleColorsClassic") void ImGui_StyleColorsClassic();
IMGUI_IMPORT("ImGui_Begin") bool ImGui_Begin(const char* name, bool* p_open, ImGuiWindowFlags flags);
IMGUI_IMPORT("ImGui_End") void ImGui_End();
IMGUI_IMPORT("ImGui_BeginChild") bool ImGui_BeginChild(const char* str_id, u64 size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags);
IMGUI_IMPORT("ImGui_BeginChild_2") bool ImGui_BeginChild_2(ImGuiID id, u64 size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags);
IMGUI_IMPORT("ImGui_EndChild") void ImGui_EndChild();
IMGUI_IMPORT("ImGui_IsWindowAppearing") bool ImGui_IsWindowAppearing();
IMGUI_IMPORT("ImGui_IsWindowCollapsed") bool ImGui_IsWindowCollapsed();
IMGUI_IMPORT("ImGui_IsWindowFocused") bool ImGui_IsWindowFocused(ImGuiFocusedFlags flags);
IMGUI_IMPORT("ImGui_IsWindowHovered") bool ImGui_IsWindowHovered(ImGuiHoveredFlags flags);
IMGUI_IMPORT("ImGui_GetWindowDrawList") u64 ImGui_GetWindowDrawList();
IMGUI_IMPORT("ImGui_GetWindowDpiScale") float ImGui_GetWindowDpiScale();
IMGUI_IMPORT("ImGui_GetWindowPos") u64 ImGui_GetWindowPos();
IMGUI_IMPORT("ImGui_GetWindowSize") u64 ImGui_GetWindowSize();
IMGUI_IMPORT("ImGui_GetWindowWidth") float ImGui_GetWindowWidth();
IMGUI_IMPORT("ImGui_GetWindowHeight") float ImGui_GetWindowHeight();
IMGUI_IMPORT("ImGui_GetWindowViewport") ImGuiID ImGui_GetWindowViewport();
IMGUI_IMPORT("ImGui_SetNextWindowPos") void ImGui_SetNextWindowPos(u64 pos, ImGuiCond cond, u64 pivot);
IMGUI_IMPORT("ImGui_SetNextWindowSize") void ImGui_SetNextWindowSize(u64 size, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetNextWindowSizeConstraints") void ImGui_SetNextWindowSizeConstraints(u64 size_min, u64 size_max);
IMGUI_IMPORT("ImGui_SetNextWindowContentSize") void ImGui_SetNextWindowContentSize(u64 size);
IMGUI_IMPORT("ImGui_SetNextWindowCollapsed") void ImGui_SetNextWindowCollapsed(bool collapsed, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetNextWindowFocus") void ImGui_SetNextWindowFocus();
IMGUI_IMPORT("ImGui_SetNextWindowScroll") void ImGui_SetNextWindowScroll(u64 scroll);
IMGUI_IMPORT("ImGui_SetNextWindowBgAlpha") void ImGui_SetNextWindowBgAlpha(float alpha);
IMGUI_IMPORT("ImGui_SetNextWindowViewport") void ImGui_SetNextWindowViewport(ImGuiID viewport_id);
IMGUI_IMPORT("ImGui_SetWindowPos") void ImGui_SetWindowPos(u64 pos, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetWindowSize") void ImGui_SetWindowSize(u64 size, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetWindowCollapsed") void ImGui_SetWindowCollapsed(bool collapsed, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetWindowFocus") void ImGui_SetWindowFocus();
IMGUI_IMPORT("ImGui_SetWindowPos_2") void ImGui_SetWindowPos_2(const char* name, u64 pos, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetWindowSize_2") void ImGui_SetWindowSize_2(const char* name, u64 size, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetWindowCollapsed_2") void ImGui_SetWindowCollapsed_2(const char* name, bool collapsed, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetWindowFocus_2") void ImGui_SetWindowFocus_2(const char* name);
IMGUI_IMPORT("ImGui_GetScrollX") float ImGui_GetScrollX();
IMGUI_IMPORT("ImGui_GetScrollY") float ImGui_GetScrollY();
IMGUI_IMPORT("ImGui_SetScrollX") void ImGui_SetScrollX(float scroll_x);
IMGUI_IMPORT("ImGui_SetScrollY") void ImGui_SetScrollY(float scroll_y);
IMGUI_IMPORT("ImGui_GetScrollMaxX") float ImGui_GetScrollMaxX();
IMGUI_IMPORT("ImGui_GetScrollMaxY") float ImGui_GetScrollMaxY();
IMGUI_IMPORT("ImGui_SetScrollHereX") void ImGui_SetScrollHereX(float center_x_ratio);
IMGUI_IMPORT("ImGui_SetScrollHereY") void ImGui_SetScrollHereY(float center_y_ratio);
IMGUI_IMPORT("ImGui_SetScrollFromPosX") void ImGui_SetScrollFromPosX(float local_x, float center_x_ratio);
IMGUI_IMPORT("ImGui_SetScrollFromPosY") void ImGui_SetScrollFromPosY(float local_y, float center_y_ratio);
IMGUI_IMPORT("ImGui_PushFont") void ImGui_PushFont(u64 font, float font_size_base_unscaled);
IMGUI_IMPORT("ImGui_PopFont") void ImGui_PopFont();
IMGUI_IMPORT("ImGui_GetFont") u64 ImGui_GetFont();
IMGUI_IMPORT("ImGui_GetFontSize") float ImGui_GetFontSize();
IMGUI_IMPORT("ImGui_PushStyleColor") void ImGui_PushStyleColor(ImGuiCol idx, ImU32 col);
IMGUI_IMPORT("ImGui_PushStyleColor_2") void ImGui_PushStyleColor_2(ImGuiCol idx, u64 col_xy, u64 col_zw);
IMGUI_IMPORT("ImGui_PopStyleColor") void ImGui_PopStyleColor(int count);
IMGUI_IMPORT("ImGui_PushStyleVar") void ImGui_PushStyleVar(ImGuiStyleVar idx, float val);
IMGUI_IMPORT("ImGui_PushStyleVar_2") void ImGui_PushStyleVar_2(ImGuiStyleVar idx, u64 val);
IMGUI_IMPORT("ImGui_PushStyleVarX") void ImGui_PushStyleVarX(ImGuiStyleVar idx, float val_x);
IMGUI_IMPORT("ImGui_PushStyleVarY") void ImGui_PushStyleVarY(ImGuiStyleVar idx, float val_y);
IMGUI_IMPORT("ImGui_PopStyleVar") void ImGui_PopStyleVar(int count);
IMGUI_IMPORT("ImGui_PushItemFlag") void ImGui_PushItemFlag(ImGuiItemFlags option, bool enabled);
IMGUI_IMPORT("ImGui_PopItemFlag") void ImGui_PopItemFlag();
IMGUI_IMPORT("ImGui_PushItemWidth") void ImGui_PushItemWidth(float item_width);
IMGUI_IMPORT("ImGui_PopItemWidth") void ImGui_PopItemWidth();
IMGUI_IMPORT("ImGui_SetNextItemWidth") void ImGui_SetNextItemWidth(float item_width);
IMGUI_IMPORT("ImGui_CalcItemWidth") float ImGui_CalcItemWidth();
IMGUI_IMPORT("ImGui_PushTextWrapPos") void ImGui_PushTextWrapPos(float wrap_local_pos_x);
IMGUI_IMPORT("ImGui_PopTextWrapPos") void ImGui_PopTextWrapPos();
IMGUI_IMPORT("ImGui_GetFontTexUvWhitePixel") u64 ImGui_GetFontTexUvWhitePixel();
IMGUI_IMPORT("ImGui_GetColorU32") ImU32 ImGui_GetColorU32(ImGuiCol idx, float alpha_mul);
IMGUI_IMPORT("ImGui_GetColorU32_2") ImU32 ImGui_GetColorU32_2(u64 col_xy, u64 col_zw);
IMGUI_IMPORT("ImGui_GetColorU32_3") ImU32 ImGui_GetColorU32_3(ImU32 col, float alpha_mul);
IMGUI_IMPORT("ImGui_GetCursorScreenPos") u64 ImGui_GetCursorScreenPos();
IMGUI_IMPORT("ImGui_SetCursorScreenPos") void ImGui_SetCursorScreenPos(u64 pos);
IMGUI_IMPORT("ImGui_GetContentRegionAvail") u64 ImGui_GetContentRegionAvail();
IMGUI_IMPORT("ImGui_GetCursorPos") u64 ImGui_GetCursorPos();
IMGUI_IMPORT("ImGui_GetCursorPosX") float ImGui_GetCursorPosX();
IMGUI_IMPORT("ImGui_GetCursorPosY") float ImGui_GetCursorPosY();
IMGUI_IMPORT("ImGui_SetCursorPos") void ImGui_SetCursorPos(u64 local_pos);
IMGUI_IMPORT("ImGui_SetCursorPosX") void ImGui_SetCursorPosX(float local_x);
IMGUI_IMPORT("ImGui_SetCursorPosY") void ImGui_SetCursorPosY(float local_y);
IMGUI_IMPORT("ImGui_GetCursorStartPos") u64 ImGui_GetCursorStartPos();
IMGUI_IMPORT("ImGui_Separator") void ImGui_Separator();
IMGUI_IMPORT("ImGui_SameLine") void ImGui_SameLine(float offset_from_start_x, float spacing);
IMGUI_IMPORT("ImGui_NewLine") void ImGui_NewLine();
IMGUI_IMPORT("ImGui_Spacing") void ImGui_Spacing();
IMGUI_IMPORT("ImGui_Dummy") void ImGui_Dummy(u64 size);
IMGUI_IMPORT("ImGui_Indent") void ImGui_Indent(float indent_w);
IMGUI_IMPORT("ImGui_Unindent") void ImGui_Unindent(float indent_w);
IMGUI_IMPORT("ImGui_BeginGroup") void ImGui_BeginGroup();
IMGUI_IMPORT("ImGui_EndGroup") void ImGui_EndGroup();
IMGUI_IMPORT("ImGui_AlignTextToFramePadding") void ImGui_AlignTextToFramePadding();
IMGUI_IMPORT("ImGui_GetTextLineHeight") float ImGui_GetTextLineHeight();
IMGUI_IMPORT("ImGui_GetTextLineHeightWithSpacing") float ImGui_GetTextLineHeightWithSpacing();
IMGUI_IMPORT("ImGui_GetFrameHeight") float ImGui_GetFrameHeight();
IMGUI_IMPORT("ImGui_GetFrameHeightWithSpacing") float ImGui_GetFrameHeightWithSpacing();
IMGUI_IMPORT("ImGui_PushID") void ImGui_PushID(const char* str_id);
IMGUI_IMPORT("ImGui_PushID_2") void ImGui_PushID_2(const char* str_id_begin, const char* str_id_end);
IMGUI_IMPORT("ImGui_PushID_3") void ImGui_PushID_3(const void* ptr_id);
IMGUI_IMPORT("ImGui_PushID_4") void ImGui_PushID_4(int int_id);
IMGUI_IMPORT("ImGui_PopID") void ImGui_PopID();
IMGUI_IMPORT("ImGui_GetID") ImGuiID ImGui_GetID(const char* str_id);
IMGUI_IMPORT("ImGui_GetID_2") ImGuiID ImGui_GetID_2(const char* str_id_begin, const char* str_id_end);
IMGUI_IMPORT("ImGui_GetID_3") ImGuiID ImGui_GetID_3(const void* ptr_id);
IMGUI_IMPORT("ImGui_GetID_4") ImGuiID ImGui_GetID_4(int int_id);
IMGUI_IMPORT("ImGui_TextUnformatted") void ImGui_TextUnformatted(const char* text, const char* text_end);
IMGUI_IMPORT("ImGui_Text") void ImGui_Text(const char* text);
IMGUI_IMPORT("ImGui_TextColored") void ImGui_TextColored(u64 col_xy, u64 col_zw, const char* text);
IMGUI_IMPORT("ImGui_TextDisabled") void ImGui_TextDisabled(const char* text);
IMGUI_IMPORT("ImGui_TextWrapped") void ImGui_TextWrapped(const char* text);
IMGUI_IMPORT("ImGui_LabelText") void ImGui_LabelText(const char* label, const char* text);
IMGUI_IMPORT("ImGui_BulletText") void ImGui_BulletText(const char* text);
IMGUI_IMPORT("ImGui_SeparatorText") void ImGui_SeparatorText(const char* label);
IMGUI_IMPORT("ImGui_Button") bool ImGui_Button(const char* label, u64 size);
IMGUI_IMPORT("ImGui_SmallButton") bool ImGui_SmallButton(const char* label);
IMGUI_IMPORT("ImGui_InvisibleButton") bool ImGui_InvisibleButton(const char* str_id, u64 size, ImGuiButtonFlags flags);
IMGUI_IMPORT("ImGui_ArrowButton") bool ImGui_ArrowButton(const char* str_id, ImGuiDir dir);
IMGUI_IMPORT("ImGui_Checkbox") bool ImGui_Checkbox(const char* label, bool* v);
IMGUI_IMPORT("ImGui_CheckboxFlags") bool ImGui_CheckboxFlags(const char* label, int* flags, int flags_value);
IMGUI_IMPORT("ImGui_CheckboxFlags_2") bool ImGui_CheckboxFlags_2(const char* label, unsigned int* flags, unsigned int flags_value);
IMGUI_IMPORT("ImGui_RadioButton") bool ImGui_RadioButton(const char* label, bool active);
IMGUI_IMPORT("ImGui_RadioButton_2") bool ImGui_RadioButton_2(const char* label, int* v, int v_button);
IMGUI_IMPORT("ImGui_ProgressBar") void ImGui_ProgressBar(float fraction, u64 size_arg, const char* overlay);
IMGUI_IMPORT("ImGui_Bullet") void ImGui_Bullet();
IMGUI_IMPORT("ImGui_TextLink") bool ImGui_TextLink(const char* label);
IMGUI_IMPORT("ImGui_TextLinkOpenURL") bool ImGui_TextLinkOpenURL(const char* label, const char* url);
IMGUI_IMPORT("ImGui_Image") void ImGui_Image(u64 tex_ref, u64 image_size, u64 uv0, u64 uv1);
IMGUI_IMPORT("ImGui_ImageWithBg") void ImGui_ImageWithBg(
    u64 tex_ref,
    u64 image_size,
    u64 uv0,
    u64 uv1,
    u64 bg_col_xy,
    u64 bg_col_zw,
    u64 tint_col_xy,
    u64 tint_col_zw
);
IMGUI_IMPORT("ImGui_ImageButton") bool ImGui_ImageButton(
    const char* str_id,
    u64 tex_ref,
    u64 image_size,
    u64 uv0,
    u64 uv1,
    u64 bg_col_xy,
    u64 bg_col_zw,
    u64 tint_col_xy,
    u64 tint_col_zw
);
IMGUI_IMPORT("ImGui_BeginCombo") bool ImGui_BeginCombo(const char* label, const char* preview_value, ImGuiComboFlags flags);
IMGUI_IMPORT("ImGui_EndCombo") void ImGui_EndCombo();
IMGUI_IMPORT("ImGui_Combo") bool ImGui_Combo(const char* label, int* current_item, const char* const* items, int items_count, int popup_max_height_in_items);
IMGUI_IMPORT("ImGui_Combo_2") bool ImGui_Combo_2(const char* label, int* current_item, const char* items_separated_by_zeros, int popup_max_height_in_items);
IMGUI_IMPORT("ImGui_DragFloat") bool ImGui_DragFloat(
    const char* label,
    float* v,
    float v_speed,
    float v_min,
    float v_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_DragFloat2") bool ImGui_DragFloat2(
    const char* label,
    float* v,
    float v_speed,
    float v_min,
    float v_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_DragFloat3") bool ImGui_DragFloat3(
    const char* label,
    float* v,
    float v_speed,
    float v_min,
    float v_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_DragFloat4") bool ImGui_DragFloat4(
    const char* label,
    float* v,
    float v_speed,
    float v_min,
    float v_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_DragFloatRange2") bool ImGui_DragFloatRange2(
    const char* label,
    float* v_current_min,
    float* v_current_max,
    float v_speed,
    float v_min,
    float v_max,
    const char* format,
    const char* format_max,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_DragInt") bool ImGui_DragInt(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_DragInt2") bool ImGui_DragInt2(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_DragInt3") bool ImGui_DragInt3(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_DragInt4") bool ImGui_DragInt4(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_DragIntRange2") bool ImGui_DragIntRange2(
    const char* label,
    int* v_current_min,
    int* v_current_max,
    float v_speed,
    int v_min,
    int v_max,
    const char* format,
    const char* format_max,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_DragScalar") bool ImGui_DragScalar(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    float v_speed,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_DragScalarN") bool ImGui_DragScalarN(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    int components,
    float v_speed,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_SliderFloat") bool ImGui_SliderFloat(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderFloat2") bool ImGui_SliderFloat2(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderFloat3") bool ImGui_SliderFloat3(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderFloat4") bool ImGui_SliderFloat4(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderAngle") bool ImGui_SliderAngle(
    const char* label,
    float* v_rad,
    float v_degrees_min,
    float v_degrees_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_SliderInt") bool ImGui_SliderInt(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderInt2") bool ImGui_SliderInt2(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderInt3") bool ImGui_SliderInt3(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderInt4") bool ImGui_SliderInt4(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_SliderScalar") bool ImGui_SliderScalar(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_SliderScalarN") bool ImGui_SliderScalarN(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    int components,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_VSliderFloat") bool ImGui_VSliderFloat(
    const char* label,
    u64 size,
    float* v,
    float v_min,
    float v_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_VSliderInt") bool ImGui_VSliderInt(const char* label, u64 size, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
IMGUI_IMPORT("ImGui_VSliderScalar") bool ImGui_VSliderScalar(
    const char* label,
    u64 size,
    ImGuiDataType data_type,
    void* p_data,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
);
IMGUI_IMPORT("ImGui_InputText") bool ImGui_InputText(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputTextMultiline") bool ImGui_InputTextMultiline(const char* label, char* buf, size_t buf_size, u64 size, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputTextWithHint") bool ImGui_InputTextWithHint(
    const char* label,
    const char* hint,
    char* buf,
    size_t buf_size,
    ImGuiInputTextFlags flags
);
IMGUI_IMPORT("ImGui_InputFloat") bool ImGui_InputFloat(const char* label, float* v, float step, float step_fast, const char* format, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputFloat2") bool ImGui_InputFloat2(const char* label, float* v, const char* format, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputFloat3") bool ImGui_InputFloat3(const char* label, float* v, const char* format, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputFloat4") bool ImGui_InputFloat4(const char* label, float* v, const char* format, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputInt") bool ImGui_InputInt(const char* label, int* v, int step, int step_fast, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputInt2") bool ImGui_InputInt2(const char* label, int* v, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputInt3") bool ImGui_InputInt3(const char* label, int* v, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputInt4") bool ImGui_InputInt4(const char* label, int* v, ImGuiInputTextFlags flags);
IMGUI_IMPORT("ImGui_InputDouble") bool ImGui_InputDouble(
    const char* label,
    double* v,
    double step,
    double step_fast,
    const char* format,
    ImGuiInputTextFlags flags
);
IMGUI_IMPORT("ImGui_InputScalar") bool ImGui_InputScalar(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    const void* p_step,
    const void* p_step_fast,
    const char* format,
    ImGuiInputTextFlags flags
);
IMGUI_IMPORT("ImGui_InputScalarN") bool ImGui_InputScalarN(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    int components,
    const void* p_step,
    const void* p_step_fast,
    const char* format,
    ImGuiInputTextFlags flags
);
IMGUI_IMPORT("ImGui_ColorEdit3") bool ImGui_ColorEdit3(const char* label, float* col, ImGuiColorEditFlags flags);
IMGUI_IMPORT("ImGui_ColorEdit4") bool ImGui_ColorEdit4(const char* label, float* col, ImGuiColorEditFlags flags);
IMGUI_IMPORT("ImGui_ColorPicker3") bool ImGui_ColorPicker3(const char* label, float* col, ImGuiColorEditFlags flags);
IMGUI_IMPORT("ImGui_ColorPicker4") bool ImGui_ColorPicker4(const char* label, float* col, ImGuiColorEditFlags flags, const float* ref_col);
IMGUI_IMPORT("ImGui_ColorButton") bool ImGui_ColorButton(const char* desc_id, u64 col_xy, u64 col_zw, ImGuiColorEditFlags flags, u64 size);
IMGUI_IMPORT("ImGui_TreeNode") bool ImGui_TreeNode(const char* label);
IMGUI_IMPORT("ImGui_TreeNode_2") bool ImGui_TreeNode_2(const char* str_id, const char* text);
IMGUI_IMPORT("ImGui_TreeNode_3") bool ImGui_TreeNode_3(const void* ptr_id, const char* text);
IMGUI_IMPORT("ImGui_TreeNodeEx") bool ImGui_TreeNodeEx(const char* label, ImGuiTreeNodeFlags flags);
IMGUI_IMPORT("ImGui_TreeNodeEx_2") bool ImGui_TreeNodeEx_2(const char* str_id, ImGuiTreeNodeFlags flags, const char* text);
IMGUI_IMPORT("ImGui_TreeNodeEx_3") bool ImGui_TreeNodeEx_3(const void* ptr_id, ImGuiTreeNodeFlags flags, const char* text);
IMGUI_IMPORT("ImGui_TreePush") void ImGui_TreePush(const char* str_id);
IMGUI_IMPORT("ImGui_TreePush_2") void ImGui_TreePush_2(const void* ptr_id);
IMGUI_IMPORT("ImGui_TreePop") void ImGui_TreePop();
IMGUI_IMPORT("ImGui_GetTreeNodeToLabelSpacing") float ImGui_GetTreeNodeToLabelSpacing();
IMGUI_IMPORT("ImGui_CollapsingHeader") bool ImGui_CollapsingHeader(const char* label, ImGuiTreeNodeFlags flags);
IMGUI_IMPORT("ImGui_CollapsingHeader_2") bool ImGui_CollapsingHeader_2(const char* label, bool* p_visible, ImGuiTreeNodeFlags flags);
IMGUI_IMPORT("ImGui_SetNextItemOpen") void ImGui_SetNextItemOpen(bool is_open, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetNextItemStorageID") void ImGui_SetNextItemStorageID(ImGuiID storage_id);
IMGUI_IMPORT("ImGui_TreeNodeGetOpen") bool ImGui_TreeNodeGetOpen(ImGuiID storage_id);
IMGUI_IMPORT("ImGui_Selectable") bool ImGui_Selectable(const char* label, bool selected, ImGuiSelectableFlags flags, u64 size);
IMGUI_IMPORT("ImGui_Selectable_2") bool ImGui_Selectable_2(const char* label, bool* p_selected, ImGuiSelectableFlags flags, u64 size);
IMGUI_IMPORT("ImGui_SetNextItemSelectionUserData") void ImGui_SetNextItemSelectionUserData(ImGuiSelectionUserData selection_user_data);
IMGUI_IMPORT("ImGui_IsItemToggledSelection") bool ImGui_IsItemToggledSelection();
IMGUI_IMPORT("ImGui_BeginListBox") bool ImGui_BeginListBox(const char* label, u64 size);
IMGUI_IMPORT("ImGui_EndListBox") void ImGui_EndListBox();
IMGUI_IMPORT("ImGui_ListBox") bool ImGui_ListBox(const char* label, int* current_item, const char* const* items, int items_count, int height_in_items);
IMGUI_IMPORT("ImGui_PlotLines") void ImGui_PlotLines(
    const char* label,
    const float* values,
    int values_count,
    int values_offset,
    const char* overlay_text,
    float scale_min,
    float scale_max,
    u64 graph_size,
    int stride
);
IMGUI_IMPORT("ImGui_PlotHistogram") void ImGui_PlotHistogram(
    const char* label,
    const float* values,
    int values_count,
    int values_offset,
    const char* overlay_text,
    float scale_min,
    float scale_max,
    u64 graph_size,
    int stride
);
IMGUI_IMPORT("ImGui_Value") void ImGui_Value(const char* prefix, bool b);
IMGUI_IMPORT("ImGui_Value_2") void ImGui_Value_2(const char* prefix, int v);
IMGUI_IMPORT("ImGui_Value_3") void ImGui_Value_3(const char* prefix, unsigned int v);
IMGUI_IMPORT("ImGui_Value_4") void ImGui_Value_4(const char* prefix, float v, const char* float_format);
IMGUI_IMPORT("ImGui_BeginMenuBar") bool ImGui_BeginMenuBar();
IMGUI_IMPORT("ImGui_EndMenuBar") void ImGui_EndMenuBar();
IMGUI_IMPORT("ImGui_BeginMainMenuBar") bool ImGui_BeginMainMenuBar();
IMGUI_IMPORT("ImGui_EndMainMenuBar") void ImGui_EndMainMenuBar();
IMGUI_IMPORT("ImGui_BeginMenu") bool ImGui_BeginMenu(const char* label, bool enabled);
IMGUI_IMPORT("ImGui_EndMenu") void ImGui_EndMenu();
IMGUI_IMPORT("ImGui_MenuItem") bool ImGui_MenuItem(const char* label, const char* shortcut, bool selected, bool enabled);
IMGUI_IMPORT("ImGui_MenuItem_2") bool ImGui_MenuItem_2(const char* label, const char* shortcut, bool* p_selected, bool enabled);
IMGUI_IMPORT("ImGui_BeginTooltip") bool ImGui_BeginTooltip();
IMGUI_IMPORT("ImGui_EndTooltip") void ImGui_EndTooltip();
IMGUI_IMPORT("ImGui_SetTooltip") void ImGui_SetTooltip(const char* text);
IMGUI_IMPORT("ImGui_BeginItemTooltip") bool ImGui_BeginItemTooltip();
IMGUI_IMPORT("ImGui_SetItemTooltip") void ImGui_SetItemTooltip(const char* text);
IMGUI_IMPORT("ImGui_BeginPopup") bool ImGui_BeginPopup(const char* str_id, ImGuiWindowFlags flags);
IMGUI_IMPORT("ImGui_BeginPopupModal") bool ImGui_BeginPopupModal(const char* name, bool* p_open, ImGuiWindowFlags flags);
IMGUI_IMPORT("ImGui_EndPopup") void ImGui_EndPopup();
IMGUI_IMPORT("ImGui_OpenPopup") bool ImGui_OpenPopup(const char* str_id, ImGuiPopupFlags popup_flags);
IMGUI_IMPORT("ImGui_OpenPopup_2") bool ImGui_OpenPopup_2(ImGuiID id, ImGuiPopupFlags popup_flags);
IMGUI_IMPORT("ImGui_OpenPopupOnItemClick") bool ImGui_OpenPopupOnItemClick(const char* str_id, ImGuiPopupFlags popup_flags);
IMGUI_IMPORT("ImGui_CloseCurrentPopup") void ImGui_CloseCurrentPopup();
IMGUI_IMPORT("ImGui_BeginPopupContextItem") bool ImGui_BeginPopupContextItem(const char* str_id, ImGuiPopupFlags popup_flags);
IMGUI_IMPORT("ImGui_BeginPopupContextWindow") bool ImGui_BeginPopupContextWindow(const char* str_id, ImGuiPopupFlags popup_flags);
IMGUI_IMPORT("ImGui_BeginPopupContextVoid") bool ImGui_BeginPopupContextVoid(const char* str_id, ImGuiPopupFlags popup_flags);
IMGUI_IMPORT("ImGui_IsPopupOpen") bool ImGui_IsPopupOpen(const char* str_id, ImGuiPopupFlags flags);
IMGUI_IMPORT("ImGui_BeginTable") bool ImGui_BeginTable(const char* str_id, int columns, ImGuiTableFlags flags, u64 outer_size, float inner_width);
IMGUI_IMPORT("ImGui_EndTable") void ImGui_EndTable();
IMGUI_IMPORT("ImGui_TableNextRow") void ImGui_TableNextRow(ImGuiTableRowFlags row_flags, float min_row_height);
IMGUI_IMPORT("ImGui_TableNextColumn") bool ImGui_TableNextColumn();
IMGUI_IMPORT("ImGui_TableSetColumnIndex") bool ImGui_TableSetColumnIndex(int column_n);
IMGUI_IMPORT("ImGui_TableSetupColumn") void ImGui_TableSetupColumn(
    const char* label,
    ImGuiTableColumnFlags flags,
    float init_width_or_weight,
    ImGuiID user_data
);
IMGUI_IMPORT("ImGui_TableSetupScrollFreeze") void ImGui_TableSetupScrollFreeze(int cols, int rows);
IMGUI_IMPORT("ImGui_TableHeader") void ImGui_TableHeader(const char* label);
IMGUI_IMPORT("ImGui_TableHeadersRow") void ImGui_TableHeadersRow();
IMGUI_IMPORT("ImGui_TableAngledHeadersRow") void ImGui_TableAngledHeadersRow();
IMGUI_IMPORT("ImGui_TableGetColumnCount") int ImGui_TableGetColumnCount();
IMGUI_IMPORT("ImGui_TableGetColumnIndex") int ImGui_TableGetColumnIndex();
IMGUI_IMPORT("ImGui_TableGetRowIndex") int ImGui_TableGetRowIndex();
IMGUI_IMPORT("ImGui_TableGetColumnName") u64 ImGui_TableGetColumnName(int column_n, char* buffer, u64 capacity);
IMGUI_IMPORT("ImGui_TableGetColumnFlags") ImGuiTableColumnFlags ImGui_TableGetColumnFlags(int column_n);
IMGUI_IMPORT("ImGui_TableSetColumnEnabled") void ImGui_TableSetColumnEnabled(int column_n, bool v);
IMGUI_IMPORT("ImGui_TableGetHoveredColumn") int ImGui_TableGetHoveredColumn();
IMGUI_IMPORT("ImGui_TableSetBgColor") void ImGui_TableSetBgColor(ImGuiTableBgTarget target, ImU32 color, int column_n);
IMGUI_IMPORT("ImGui_Columns") void ImGui_Columns(int count, const char* id, bool borders);
IMGUI_IMPORT("ImGui_NextColumn") void ImGui_NextColumn();
IMGUI_IMPORT("ImGui_GetColumnIndex") int ImGui_GetColumnIndex();
IMGUI_IMPORT("ImGui_GetColumnWidth") float ImGui_GetColumnWidth(int column_index);
IMGUI_IMPORT("ImGui_SetColumnWidth") void ImGui_SetColumnWidth(int column_index, float width);
IMGUI_IMPORT("ImGui_GetColumnOffset") float ImGui_GetColumnOffset(int column_index);
IMGUI_IMPORT("ImGui_SetColumnOffset") void ImGui_SetColumnOffset(int column_index, float offset_x);
IMGUI_IMPORT("ImGui_GetColumnsCount") int ImGui_GetColumnsCount();
IMGUI_IMPORT("ImGui_BeginTabBar") bool ImGui_BeginTabBar(const char* str_id, ImGuiTabBarFlags flags);
IMGUI_IMPORT("ImGui_EndTabBar") void ImGui_EndTabBar();
IMGUI_IMPORT("ImGui_BeginTabItem") bool ImGui_BeginTabItem(const char* label, bool* p_open, ImGuiTabItemFlags flags);
IMGUI_IMPORT("ImGui_EndTabItem") void ImGui_EndTabItem();
IMGUI_IMPORT("ImGui_TabItemButton") bool ImGui_TabItemButton(const char* label, ImGuiTabItemFlags flags);
IMGUI_IMPORT("ImGui_SetTabItemClosed") void ImGui_SetTabItemClosed(const char* tab_or_docked_window_label);
IMGUI_IMPORT("ImGui_DockSpace") ImGuiID ImGui_DockSpace(ImGuiID dockspace_id, u64 size, ImGuiDockNodeFlags flags, const ImGuiWindowClass* window_class);
IMGUI_IMPORT("ImGui_DockSpaceOverViewport") ImGuiID ImGui_DockSpaceOverViewport(
    ImGuiID dockspace_id,
    ImGuiID viewport,
    ImGuiDockNodeFlags flags,
    const ImGuiWindowClass* window_class
);
IMGUI_IMPORT("ImGui_SetNextWindowDockID") void ImGui_SetNextWindowDockID(ImGuiID dock_id, ImGuiCond cond);
IMGUI_IMPORT("ImGui_SetNextWindowClass") void ImGui_SetNextWindowClass(const ImGuiWindowClass* window_class);
IMGUI_IMPORT("ImGui_GetWindowDockID") ImGuiID ImGui_GetWindowDockID();
IMGUI_IMPORT("ImGui_IsWindowDocked") bool ImGui_IsWindowDocked();
IMGUI_IMPORT("ImGui_LogToTTY") void ImGui_LogToTTY(int auto_open_depth);
IMGUI_IMPORT("ImGui_LogToClipboard") void ImGui_LogToClipboard(int auto_open_depth);
IMGUI_IMPORT("ImGui_LogFinish") void ImGui_LogFinish();
IMGUI_IMPORT("ImGui_LogText") void ImGui_LogText(const char* text);
IMGUI_IMPORT("ImGui_BeginDragDropSource") bool ImGui_BeginDragDropSource(ImGuiDragDropFlags flags);
IMGUI_IMPORT("ImGui_SetDragDropPayload") bool ImGui_SetDragDropPayload(const char* type, const void* data, size_t sz, ImGuiCond cond);
IMGUI_IMPORT("ImGui_EndDragDropSource") void ImGui_EndDragDropSource();
IMGUI_IMPORT("ImGui_BeginDragDropTarget") bool ImGui_BeginDragDropTarget();
IMGUI_IMPORT("ImGui_EndDragDropTarget") void ImGui_EndDragDropTarget();
IMGUI_IMPORT("ImGui_BeginDisabled") void ImGui_BeginDisabled(bool disabled);
IMGUI_IMPORT("ImGui_EndDisabled") void ImGui_EndDisabled();
IMGUI_IMPORT("ImGui_PushClipRect") void ImGui_PushClipRect(u64 clip_rect_min, u64 clip_rect_max, bool intersect_with_current_clip_rect);
IMGUI_IMPORT("ImGui_PopClipRect") void ImGui_PopClipRect();
IMGUI_IMPORT("ImGui_SetItemDefaultFocus") void ImGui_SetItemDefaultFocus();
IMGUI_IMPORT("ImGui_SetKeyboardFocusHere") void ImGui_SetKeyboardFocusHere(int offset);
IMGUI_IMPORT("ImGui_SetNavCursorVisible") void ImGui_SetNavCursorVisible(bool visible);
IMGUI_IMPORT("ImGui_SetNextItemAllowOverlap") void ImGui_SetNextItemAllowOverlap();
IMGUI_IMPORT("ImGui_IsItemHovered") bool ImGui_IsItemHovered(ImGuiHoveredFlags flags);
IMGUI_IMPORT("ImGui_IsItemActive") bool ImGui_IsItemActive();
IMGUI_IMPORT("ImGui_IsItemFocused") bool ImGui_IsItemFocused();
IMGUI_IMPORT("ImGui_IsItemClicked") bool ImGui_IsItemClicked(ImGuiMouseButton mouse_button);
IMGUI_IMPORT("ImGui_IsItemVisible") bool ImGui_IsItemVisible();
IMGUI_IMPORT("ImGui_IsItemEdited") bool ImGui_IsItemEdited();
IMGUI_IMPORT("ImGui_IsItemActivated") bool ImGui_IsItemActivated();
IMGUI_IMPORT("ImGui_IsItemDeactivated") bool ImGui_IsItemDeactivated();
IMGUI_IMPORT("ImGui_IsItemDeactivatedAfterEdit") bool ImGui_IsItemDeactivatedAfterEdit();
IMGUI_IMPORT("ImGui_IsItemToggledOpen") bool ImGui_IsItemToggledOpen();
IMGUI_IMPORT("ImGui_IsAnyItemHovered") bool ImGui_IsAnyItemHovered();
IMGUI_IMPORT("ImGui_IsAnyItemActive") bool ImGui_IsAnyItemActive();
IMGUI_IMPORT("ImGui_IsAnyItemFocused") bool ImGui_IsAnyItemFocused();
IMGUI_IMPORT("ImGui_GetItemID") ImGuiID ImGui_GetItemID();
IMGUI_IMPORT("ImGui_GetItemRectMin") u64 ImGui_GetItemRectMin();
IMGUI_IMPORT("ImGui_GetItemRectMax") u64 ImGui_GetItemRectMax();
IMGUI_IMPORT("ImGui_GetItemRectSize") u64 ImGui_GetItemRectSize();
IMGUI_IMPORT("ImGui_GetItemFlags") ImGuiItemFlags ImGui_GetItemFlags();
IMGUI_IMPORT("ImGui_GetItemClickedCountWithSingleClickDelay") int ImGui_GetItemClickedCountWithSingleClickDelay(ImGuiMouseButton mouse_button, float delay);
IMGUI_IMPORT("ImGui_GetMainViewport") ImGuiID ImGui_GetMainViewport();
IMGUI_IMPORT("ImGui_GetBackgroundDrawList") u64 ImGui_GetBackgroundDrawList(ImGuiID viewport);
IMGUI_IMPORT("ImGui_GetForegroundDrawList") u64 ImGui_GetForegroundDrawList(ImGuiID viewport);
IMGUI_IMPORT("ImGui_IsRectVisible") bool ImGui_IsRectVisible(u64 size);
IMGUI_IMPORT("ImGui_IsRectVisible_2") bool ImGui_IsRectVisible_2(u64 rect_min, u64 rect_max);
IMGUI_IMPORT("ImGui_GetTime") double ImGui_GetTime();
IMGUI_IMPORT("ImGui_GetFrameCount") int ImGui_GetFrameCount();
IMGUI_IMPORT("ImGui_GetStyleColorName") u64 ImGui_GetStyleColorName(ImGuiCol idx, char* buffer, u64 capacity);
IMGUI_IMPORT("ImGui_CalcTextSize") u64 ImGui_CalcTextSize(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width);
IMGUI_IMPORT("ImGui_ColorConvertU32ToFloat4") void ImGui_ColorConvertU32ToFloat4(ImU32 in, ImVec4* result);
IMGUI_IMPORT("ImGui_ColorConvertFloat4ToU32") ImU32 ImGui_ColorConvertFloat4ToU32(u64 in_xy, u64 in_zw);
IMGUI_IMPORT("ImGui_ColorConvertRGBtoHSV") void ImGui_ColorConvertRGBtoHSV(float r, float g, float b, float* out_h, float* out_s, float* out_v);
IMGUI_IMPORT("ImGui_ColorConvertHSVtoRGB") void ImGui_ColorConvertHSVtoRGB(float h, float s, float v, float* out_r, float* out_g, float* out_b);
IMGUI_IMPORT("ImGui_IsKeyDown") bool ImGui_IsKeyDown(ImGuiKey key);
IMGUI_IMPORT("ImGui_IsKeyPressed") bool ImGui_IsKeyPressed(ImGuiKey key, bool repeat);
IMGUI_IMPORT("ImGui_IsKeyReleased") bool ImGui_IsKeyReleased(ImGuiKey key);
IMGUI_IMPORT("ImGui_IsKeyChordPressed") bool ImGui_IsKeyChordPressed(ImGuiKeyChord key_chord);
IMGUI_IMPORT("ImGui_GetKeyPressedAmount") int ImGui_GetKeyPressedAmount(ImGuiKey key, float repeat_delay, float rate);
IMGUI_IMPORT("ImGui_GetKeyName") u64 ImGui_GetKeyName(ImGuiKey key, char* buffer, u64 capacity);
IMGUI_IMPORT("ImGui_SetNextFrameWantCaptureKeyboard") void ImGui_SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard);
IMGUI_IMPORT("ImGui_Shortcut") bool ImGui_Shortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags);
IMGUI_IMPORT("ImGui_SetNextItemShortcut") void ImGui_SetNextItemShortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags);
IMGUI_IMPORT("ImGui_SetItemKeyOwner") bool ImGui_SetItemKeyOwner(ImGuiKey key);
IMGUI_IMPORT("ImGui_IsMouseDown") bool ImGui_IsMouseDown(ImGuiMouseButton button);
IMGUI_IMPORT("ImGui_IsMouseClicked") bool ImGui_IsMouseClicked(ImGuiMouseButton button, bool repeat);
IMGUI_IMPORT("ImGui_IsMouseReleased") bool ImGui_IsMouseReleased(ImGuiMouseButton button);
IMGUI_IMPORT("ImGui_IsMouseDoubleClicked") bool ImGui_IsMouseDoubleClicked(ImGuiMouseButton button);
IMGUI_IMPORT("ImGui_IsMouseReleasedWithDelay") bool ImGui_IsMouseReleasedWithDelay(ImGuiMouseButton button, float delay);
IMGUI_IMPORT("ImGui_GetMouseClickedCount") int ImGui_GetMouseClickedCount(ImGuiMouseButton button);
IMGUI_IMPORT("ImGui_IsMouseHoveringRect") bool ImGui_IsMouseHoveringRect(u64 r_min, u64 r_max, bool clip);
IMGUI_IMPORT("ImGui_IsMousePosValid") bool ImGui_IsMousePosValid(const ImVec2* mouse_pos);
IMGUI_IMPORT("ImGui_IsAnyMouseDown") bool ImGui_IsAnyMouseDown();
IMGUI_IMPORT("ImGui_GetMousePos") u64 ImGui_GetMousePos();
IMGUI_IMPORT("ImGui_GetMousePosOnOpeningCurrentPopup") u64 ImGui_GetMousePosOnOpeningCurrentPopup();
IMGUI_IMPORT("ImGui_IsMouseDragging") bool ImGui_IsMouseDragging(ImGuiMouseButton button, float lock_threshold);
IMGUI_IMPORT("ImGui_GetMouseDragDelta") u64 ImGui_GetMouseDragDelta(ImGuiMouseButton button, float lock_threshold);
IMGUI_IMPORT("ImGui_ResetMouseDragDelta") void ImGui_ResetMouseDragDelta(ImGuiMouseButton button);
IMGUI_IMPORT("ImGui_GetMouseCursor") ImGuiMouseCursor ImGui_GetMouseCursor();
IMGUI_IMPORT("ImGui_SetMouseCursor") void ImGui_SetMouseCursor(ImGuiMouseCursor cursor_type);
IMGUI_IMPORT("ImGui_SetNextFrameWantCaptureMouse") void ImGui_SetNextFrameWantCaptureMouse(bool want_capture_mouse);
IMGUI_IMPORT("ImGui_GetClipboardText") u64 ImGui_GetClipboardText(char* buffer, u64 capacity);
IMGUI_IMPORT("ImGui_SetClipboardText") void ImGui_SetClipboardText(const char* text);
IMGUI_IMPORT("ImGui_DebugTextEncoding") void ImGui_DebugTextEncoding(const char* text);
IMGUI_IMPORT("ImGui_DebugFlashStyleColor") void ImGui_DebugFlashStyleColor(ImGuiCol idx);
IMGUI_IMPORT("ImGui_DebugStartItemPicker") void ImGui_DebugStartItemPicker();
IMGUI_IMPORT("ImGui_DebugLog") void ImGui_DebugLog(const char* text);
IMGUI_IMPORT("ImGui_FindViewportByID") ImGuiID ImGui_FindViewportByID(ImGuiID viewport_id);
IMGUI_IMPORT("ImDrawList_PushClipRect") void ImDrawList_PushClipRect(u64 list, u64 clip_rect_min, u64 clip_rect_max, bool intersect_with_current_clip_rect);
IMGUI_IMPORT("ImDrawList_PushClipRectFullScreen") void ImDrawList_PushClipRectFullScreen(u64 list);
IMGUI_IMPORT("ImDrawList_PopClipRect") void ImDrawList_PopClipRect(u64 list);
IMGUI_IMPORT("ImDrawList_PushTexture") void ImDrawList_PushTexture(u64 list, u64 tex_ref);
IMGUI_IMPORT("ImDrawList_PopTexture") void ImDrawList_PopTexture(u64 list);
IMGUI_IMPORT("ImDrawList_AddLine") void ImDrawList_AddLine(u64 list, u64 p1, u64 p2, ImU32 col, float thickness);
IMGUI_IMPORT("ImDrawList_AddLineH") void ImDrawList_AddLineH(u64 list, float min_x, float max_x, float y, ImU32 col, float thickness);
IMGUI_IMPORT("ImDrawList_AddLineV") void ImDrawList_AddLineV(u64 list, float x, float min_y, float max_y, ImU32 col, float thickness);
IMGUI_IMPORT("ImDrawList_AddRect") void ImDrawList_AddRect(u64 list, u64 p_min, u64 p_max, ImU32 col, float rounding, float thickness, ImDrawFlags flags);
IMGUI_IMPORT("ImDrawList_AddRectFilled") void ImDrawList_AddRectFilled(u64 list, u64 p_min, u64 p_max, ImU32 col, float rounding, ImDrawFlags flags);
IMGUI_IMPORT("ImDrawList_AddRectFilledMultiColor") void ImDrawList_AddRectFilledMultiColor(
    u64 list,
    u64 p_min,
    u64 p_max,
    ImU32 col_upr_left,
    ImU32 col_upr_right,
    ImU32 col_bot_right,
    ImU32 col_bot_left
);
IMGUI_IMPORT("ImDrawList_AddQuad") void ImDrawList_AddQuad(u64 list, u64 p1, u64 p2, u64 p3, u64 p4, ImU32 col, float thickness);
IMGUI_IMPORT("ImDrawList_AddQuadFilled") void ImDrawList_AddQuadFilled(u64 list, u64 p1, u64 p2, u64 p3, u64 p4, ImU32 col);
IMGUI_IMPORT("ImDrawList_AddTriangle") void ImDrawList_AddTriangle(u64 list, u64 p1, u64 p2, u64 p3, ImU32 col, float thickness);
IMGUI_IMPORT("ImDrawList_AddTriangleFilled") void ImDrawList_AddTriangleFilled(u64 list, u64 p1, u64 p2, u64 p3, ImU32 col);
IMGUI_IMPORT("ImDrawList_AddCircle") void ImDrawList_AddCircle(u64 list, u64 center, float radius, ImU32 col, int num_segments, float thickness);
IMGUI_IMPORT("ImDrawList_AddCircleFilled") void ImDrawList_AddCircleFilled(u64 list, u64 center, float radius, ImU32 col, int num_segments);
IMGUI_IMPORT("ImDrawList_AddNgon") void ImDrawList_AddNgon(u64 list, u64 center, float radius, ImU32 col, int num_segments, float thickness);
IMGUI_IMPORT("ImDrawList_AddNgonFilled") void ImDrawList_AddNgonFilled(u64 list, u64 center, float radius, ImU32 col, int num_segments);
IMGUI_IMPORT("ImDrawList_AddEllipse") void ImDrawList_AddEllipse(u64 list, u64 center, u64 radius, ImU32 col, float rot, int num_segments, float thickness);
IMGUI_IMPORT("ImDrawList_AddEllipseFilled") void ImDrawList_AddEllipseFilled(u64 list, u64 center, u64 radius, ImU32 col, float rot, int num_segments);
IMGUI_IMPORT("ImDrawList_AddText") void ImDrawList_AddText(u64 list, u64 pos, ImU32 col, const char* text_begin, const char* text_end);
IMGUI_IMPORT("ImDrawList_AddText_2") void ImDrawList_AddText_2(
    u64 list,
    u64 font,
    float font_size,
    u64 pos,
    ImU32 col,
    const char* text_begin,
    const char* text_end,
    float wrap_width,
    const ImVec4* cpu_fine_clip_rect
);
IMGUI_IMPORT("ImDrawList_AddBezierCubic") void ImDrawList_AddBezierCubic(
    u64 list,
    u64 p1,
    u64 p2,
    u64 p3,
    u64 p4,
    ImU32 col,
    float thickness,
    int num_segments
);
IMGUI_IMPORT("ImDrawList_AddBezierQuadratic") void ImDrawList_AddBezierQuadratic(
    u64 list,
    u64 p1,
    u64 p2,
    u64 p3,
    ImU32 col,
    float thickness,
    int num_segments
);
IMGUI_IMPORT("ImDrawList_AddPolyline") void ImDrawList_AddPolyline(
    u64 list,
    const ImVec2* points,
    int num_points,
    ImU32 col,
    float thickness,
    ImDrawFlags flags
);
IMGUI_IMPORT("ImDrawList_AddConvexPolyFilled") void ImDrawList_AddConvexPolyFilled(u64 list, const ImVec2* points, int num_points, ImU32 col);
IMGUI_IMPORT("ImDrawList_AddConcavePolyFilled") void ImDrawList_AddConcavePolyFilled(u64 list, const ImVec2* points, int num_points, ImU32 col);
IMGUI_IMPORT("ImDrawList_AddImage") void ImDrawList_AddImage(u64 list, u64 tex_ref, u64 p_min, u64 p_max, u64 uv_min, u64 uv_max, ImU32 col);
IMGUI_IMPORT("ImDrawList_AddImageQuad") void ImDrawList_AddImageQuad(
    u64 list,
    u64 tex_ref,
    u64 p1,
    u64 p2,
    u64 p3,
    u64 p4,
    u64 uv1,
    u64 uv2,
    u64 uv3,
    u64 uv4,
    ImU32 col
);
IMGUI_IMPORT("ImDrawList_AddImageRounded") void ImDrawList_AddImageRounded(
    u64 list,
    u64 tex_ref,
    u64 p_min,
    u64 p_max,
    u64 uv_min,
    u64 uv_max,
    ImU32 col,
    float rounding,
    ImDrawFlags flags
);
IMGUI_IMPORT("ImDrawList_PathArcTo") void ImDrawList_PathArcTo(u64 list, u64 center, float radius, float a_min, float a_max, int num_segments);
IMGUI_IMPORT("ImDrawList_PathArcToFast") void ImDrawList_PathArcToFast(u64 list, u64 center, float radius, int a_min_of_12, int a_max_of_12);
IMGUI_IMPORT("ImDrawList_PathEllipticalArcTo") void ImDrawList_PathEllipticalArcTo(
    u64 list,
    u64 center,
    u64 radius,
    float rot,
    float a_min,
    float a_max,
    int num_segments
);
IMGUI_IMPORT("ImDrawList_PathBezierCubicCurveTo") void ImDrawList_PathBezierCubicCurveTo(u64 list, u64 p2, u64 p3, u64 p4, int num_segments);
IMGUI_IMPORT("ImDrawList_PathBezierQuadraticCurveTo") void ImDrawList_PathBezierQuadraticCurveTo(u64 list, u64 p2, u64 p3, int num_segments);
IMGUI_IMPORT("ImDrawList_PathRect") void ImDrawList_PathRect(u64 list, u64 rect_min, u64 rect_max, float rounding, ImDrawFlags flags);
IMGUI_IMPORT("ImDrawList_AddDrawCmd") void ImDrawList_AddDrawCmd(u64 list);

}

void ImGui::ShowDemoWindow(bool* p_open) {
    ImGui_ShowDemoWindow(p_open);
}

void ImGui::ShowMetricsWindow(bool* p_open) {
    ImGui_ShowMetricsWindow(p_open);
}

void ImGui::ShowDebugLogWindow(bool* p_open) {
    ImGui_ShowDebugLogWindow(p_open);
}

void ImGui::ShowIDStackToolWindow(bool* p_open) {
    ImGui_ShowIDStackToolWindow(p_open);
}

void ImGui::ShowAboutWindow(bool* p_open) {
    ImGui_ShowAboutWindow(p_open);
}

void ImGui::ShowStyleEditor(ImGuiStyle*) {
    ImGui_ShowStyleEditor();
}

bool ImGui::ShowStyleSelector(const char* label) {
    return ImGui_ShowStyleSelector(label);
}

void ImGui::ShowFontSelector(const char* label) {
    ImGui_ShowFontSelector(label);
}

void ImGui::ShowUserGuide() {
    ImGui_ShowUserGuide();
}

const char* ImGui::GetVersion() {
    u64 capacity = 256;
    char* buffer = Imgui::Scratch_Text(capacity);
    u64 length = ImGui_GetVersion(buffer, capacity);

    if (length >= capacity) {
        capacity = length + 1;
        buffer = Imgui::Scratch_Text(capacity);
        ImGui_GetVersion(buffer, capacity);
    }
    return buffer;
}

void ImGui::StyleColorsDark(ImGuiStyle*) {
    ImGui_StyleColorsDark();
}

void ImGui::StyleColorsLight(ImGuiStyle*) {
    ImGui_StyleColorsLight();
}

void ImGui::StyleColorsClassic(ImGuiStyle*) {
    ImGui_StyleColorsClassic();
}

bool ImGui::Begin(const char* name, bool* p_open, ImGuiWindowFlags flags) {
    return ImGui_Begin(name, p_open, flags);
}

void ImGui::End() {
    ImGui_End();
}

bool ImGui::BeginChild(const char* str_id, const ImVec2& size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags) {
    return ImGui_BeginChild(str_id, Imgui::Pack(size), child_flags, window_flags);
}

bool ImGui::BeginChild(ImGuiID id, const ImVec2& size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags) {
    return ImGui_BeginChild_2(id, Imgui::Pack(size), child_flags, window_flags);
}

void ImGui::EndChild() {
    ImGui_EndChild();
}

bool ImGui::IsWindowAppearing() {
    return ImGui_IsWindowAppearing();
}

bool ImGui::IsWindowCollapsed() {
    return ImGui_IsWindowCollapsed();
}

bool ImGui::IsWindowFocused(ImGuiFocusedFlags flags) {
    return ImGui_IsWindowFocused(flags);
}

bool ImGui::IsWindowHovered(ImGuiHoveredFlags flags) {
    return ImGui_IsWindowHovered(flags);
}

ImDrawList* ImGui::GetWindowDrawList() {
    return Imgui::Draw_List(ImGui_GetWindowDrawList());
}

float ImGui::GetWindowDpiScale() {
    return ImGui_GetWindowDpiScale();
}

ImVec2 ImGui::GetWindowPos() {
    return Imgui::Unpack(ImGui_GetWindowPos());
}

ImVec2 ImGui::GetWindowSize() {
    return Imgui::Unpack(ImGui_GetWindowSize());
}

float ImGui::GetWindowWidth() {
    return ImGui_GetWindowWidth();
}

float ImGui::GetWindowHeight() {
    return ImGui_GetWindowHeight();
}

ImGuiViewport* ImGui::GetWindowViewport() {
    return Imgui::Viewport(ImGui_GetWindowViewport());
}

void ImGui::SetNextWindowPos(const ImVec2& pos, ImGuiCond cond, const ImVec2& pivot) {
    ImGui_SetNextWindowPos(Imgui::Pack(pos), cond, Imgui::Pack(pivot));
}

void ImGui::SetNextWindowSize(const ImVec2& size, ImGuiCond cond) {
    ImGui_SetNextWindowSize(Imgui::Pack(size), cond);
}

void ImGui::SetNextWindowSizeConstraints(const ImVec2& size_min, const ImVec2& size_max, ImGuiSizeCallback, void*) {
    ImGui_SetNextWindowSizeConstraints(Imgui::Pack(size_min), Imgui::Pack(size_max));
}

void ImGui::SetNextWindowContentSize(const ImVec2& size) {
    ImGui_SetNextWindowContentSize(Imgui::Pack(size));
}

void ImGui::SetNextWindowCollapsed(bool collapsed, ImGuiCond cond) {
    ImGui_SetNextWindowCollapsed(collapsed, cond);
}

void ImGui::SetNextWindowFocus() {
    ImGui_SetNextWindowFocus();
}

void ImGui::SetNextWindowScroll(const ImVec2& scroll) {
    ImGui_SetNextWindowScroll(Imgui::Pack(scroll));
}

void ImGui::SetNextWindowBgAlpha(float alpha) {
    ImGui_SetNextWindowBgAlpha(alpha);
}

void ImGui::SetNextWindowViewport(ImGuiID viewport_id) {
    ImGui_SetNextWindowViewport(viewport_id);
}

void ImGui::SetWindowPos(const ImVec2& pos, ImGuiCond cond) {
    ImGui_SetWindowPos(Imgui::Pack(pos), cond);
}

void ImGui::SetWindowSize(const ImVec2& size, ImGuiCond cond) {
    ImGui_SetWindowSize(Imgui::Pack(size), cond);
}

void ImGui::SetWindowCollapsed(bool collapsed, ImGuiCond cond) {
    ImGui_SetWindowCollapsed(collapsed, cond);
}

void ImGui::SetWindowFocus() {
    ImGui_SetWindowFocus();
}

void ImGui::SetWindowPos(const char* name, const ImVec2& pos, ImGuiCond cond) {
    ImGui_SetWindowPos_2(name, Imgui::Pack(pos), cond);
}

void ImGui::SetWindowSize(const char* name, const ImVec2& size, ImGuiCond cond) {
    ImGui_SetWindowSize_2(name, Imgui::Pack(size), cond);
}

void ImGui::SetWindowCollapsed(const char* name, bool collapsed, ImGuiCond cond) {
    ImGui_SetWindowCollapsed_2(name, collapsed, cond);
}

void ImGui::SetWindowFocus(const char* name) {
    ImGui_SetWindowFocus_2(name);
}

float ImGui::GetScrollX() {
    return ImGui_GetScrollX();
}

float ImGui::GetScrollY() {
    return ImGui_GetScrollY();
}

void ImGui::SetScrollX(float scroll_x) {
    ImGui_SetScrollX(scroll_x);
}

void ImGui::SetScrollY(float scroll_y) {
    ImGui_SetScrollY(scroll_y);
}

float ImGui::GetScrollMaxX() {
    return ImGui_GetScrollMaxX();
}

float ImGui::GetScrollMaxY() {
    return ImGui_GetScrollMaxY();
}

void ImGui::SetScrollHereX(float center_x_ratio) {
    ImGui_SetScrollHereX(center_x_ratio);
}

void ImGui::SetScrollHereY(float center_y_ratio) {
    ImGui_SetScrollHereY(center_y_ratio);
}

void ImGui::SetScrollFromPosX(float local_x, float center_x_ratio) {
    ImGui_SetScrollFromPosX(local_x, center_x_ratio);
}

void ImGui::SetScrollFromPosY(float local_y, float center_y_ratio) {
    ImGui_SetScrollFromPosY(local_y, center_y_ratio);
}

void ImGui::PushFont(ImFont* font, float font_size_base_unscaled) {
    ImGui_PushFont(Imgui::Font_Handle(font), font_size_base_unscaled);
}

void ImGui::PopFont() {
    ImGui_PopFont();
}

ImFont* ImGui::GetFont() {
    return Imgui::Font(ImGui_GetFont());
}

float ImGui::GetFontSize() {
    return ImGui_GetFontSize();
}

void ImGui::PushStyleColor(ImGuiCol idx, ImU32 col) {
    ImGui_PushStyleColor(idx, col);
}

void ImGui::PushStyleColor(ImGuiCol idx, const ImVec4& col) {
    ImGui_PushStyleColor_2(idx, Imgui::Pack_Low(col), Imgui::Pack_High(col));
}

void ImGui::PopStyleColor(int count) {
    ImGui_PopStyleColor(count);
}

void ImGui::PushStyleVar(ImGuiStyleVar idx, float val) {
    ImGui_PushStyleVar(idx, val);
}

void ImGui::PushStyleVar(ImGuiStyleVar idx, const ImVec2& val) {
    ImGui_PushStyleVar_2(idx, Imgui::Pack(val));
}

void ImGui::PushStyleVarX(ImGuiStyleVar idx, float val_x) {
    ImGui_PushStyleVarX(idx, val_x);
}

void ImGui::PushStyleVarY(ImGuiStyleVar idx, float val_y) {
    ImGui_PushStyleVarY(idx, val_y);
}

void ImGui::PopStyleVar(int count) {
    ImGui_PopStyleVar(count);
}

void ImGui::PushItemFlag(ImGuiItemFlags option, bool enabled) {
    ImGui_PushItemFlag(option, enabled);
}

void ImGui::PopItemFlag() {
    ImGui_PopItemFlag();
}

void ImGui::PushItemWidth(float item_width) {
    ImGui_PushItemWidth(item_width);
}

void ImGui::PopItemWidth() {
    ImGui_PopItemWidth();
}

void ImGui::SetNextItemWidth(float item_width) {
    ImGui_SetNextItemWidth(item_width);
}

float ImGui::CalcItemWidth() {
    return ImGui_CalcItemWidth();
}

void ImGui::PushTextWrapPos(float wrap_local_pos_x) {
    ImGui_PushTextWrapPos(wrap_local_pos_x);
}

void ImGui::PopTextWrapPos() {
    ImGui_PopTextWrapPos();
}

ImVec2 ImGui::GetFontTexUvWhitePixel() {
    return Imgui::Unpack(ImGui_GetFontTexUvWhitePixel());
}

ImU32 ImGui::GetColorU32(ImGuiCol idx, float alpha_mul) {
    return ImGui_GetColorU32(idx, alpha_mul);
}

ImU32 ImGui::GetColorU32(const ImVec4& col) {
    return ImGui_GetColorU32_2(Imgui::Pack_Low(col), Imgui::Pack_High(col));
}

ImU32 ImGui::GetColorU32(ImU32 col, float alpha_mul) {
    return ImGui_GetColorU32_3(col, alpha_mul);
}

ImVec2 ImGui::GetCursorScreenPos() {
    return Imgui::Unpack(ImGui_GetCursorScreenPos());
}

void ImGui::SetCursorScreenPos(const ImVec2& pos) {
    ImGui_SetCursorScreenPos(Imgui::Pack(pos));
}

ImVec2 ImGui::GetContentRegionAvail() {
    return Imgui::Unpack(ImGui_GetContentRegionAvail());
}

ImVec2 ImGui::GetCursorPos() {
    return Imgui::Unpack(ImGui_GetCursorPos());
}

float ImGui::GetCursorPosX() {
    return ImGui_GetCursorPosX();
}

float ImGui::GetCursorPosY() {
    return ImGui_GetCursorPosY();
}

void ImGui::SetCursorPos(const ImVec2& local_pos) {
    ImGui_SetCursorPos(Imgui::Pack(local_pos));
}

void ImGui::SetCursorPosX(float local_x) {
    ImGui_SetCursorPosX(local_x);
}

void ImGui::SetCursorPosY(float local_y) {
    ImGui_SetCursorPosY(local_y);
}

ImVec2 ImGui::GetCursorStartPos() {
    return Imgui::Unpack(ImGui_GetCursorStartPos());
}

void ImGui::Separator() {
    ImGui_Separator();
}

void ImGui::SameLine(float offset_from_start_x, float spacing) {
    ImGui_SameLine(offset_from_start_x, spacing);
}

void ImGui::NewLine() {
    ImGui_NewLine();
}

void ImGui::Spacing() {
    ImGui_Spacing();
}

void ImGui::Dummy(const ImVec2& size) {
    ImGui_Dummy(Imgui::Pack(size));
}

void ImGui::Indent(float indent_w) {
    ImGui_Indent(indent_w);
}

void ImGui::Unindent(float indent_w) {
    ImGui_Unindent(indent_w);
}

void ImGui::BeginGroup() {
    ImGui_BeginGroup();
}

void ImGui::EndGroup() {
    ImGui_EndGroup();
}

void ImGui::AlignTextToFramePadding() {
    ImGui_AlignTextToFramePadding();
}

float ImGui::GetTextLineHeight() {
    return ImGui_GetTextLineHeight();
}

float ImGui::GetTextLineHeightWithSpacing() {
    return ImGui_GetTextLineHeightWithSpacing();
}

float ImGui::GetFrameHeight() {
    return ImGui_GetFrameHeight();
}

float ImGui::GetFrameHeightWithSpacing() {
    return ImGui_GetFrameHeightWithSpacing();
}

void ImGui::PushID(const char* str_id) {
    ImGui_PushID(str_id);
}

void ImGui::PushID(const char* str_id_begin, const char* str_id_end) {
    ImGui_PushID_2(str_id_begin, str_id_end);
}

void ImGui::PushID(const void* ptr_id) {
    ImGui_PushID_3(ptr_id);
}

void ImGui::PushID(int int_id) {
    ImGui_PushID_4(int_id);
}

void ImGui::PopID() {
    ImGui_PopID();
}

ImGuiID ImGui::GetID(const char* str_id) {
    return ImGui_GetID(str_id);
}

ImGuiID ImGui::GetID(const char* str_id_begin, const char* str_id_end) {
    return ImGui_GetID_2(str_id_begin, str_id_end);
}

ImGuiID ImGui::GetID(const void* ptr_id) {
    return ImGui_GetID_3(ptr_id);
}

ImGuiID ImGui::GetID(int int_id) {
    return ImGui_GetID_4(int_id);
}

void ImGui::TextUnformatted(const char* text, const char* text_end) {
    ImGui_TextUnformatted(text, text_end);
}

void ImGui::Text(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_Text(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::TextV(const char* fmt, va_list args) {
    ImGui_Text(Imgui::Format(fmt, args));
}

void ImGui::TextColored(const ImVec4& col, const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_TextColored(Imgui::Pack_Low(col), Imgui::Pack_High(col), Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::TextColoredV(const ImVec4& col, const char* fmt, va_list args) {
    ImGui_TextColored(Imgui::Pack_Low(col), Imgui::Pack_High(col), Imgui::Format(fmt, args));
}

void ImGui::TextDisabled(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_TextDisabled(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::TextDisabledV(const char* fmt, va_list args) {
    ImGui_TextDisabled(Imgui::Format(fmt, args));
}

void ImGui::TextWrapped(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_TextWrapped(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::TextWrappedV(const char* fmt, va_list args) {
    ImGui_TextWrapped(Imgui::Format(fmt, args));
}

void ImGui::LabelText(const char* label, const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_LabelText(label, Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::LabelTextV(const char* label, const char* fmt, va_list args) {
    ImGui_LabelText(label, Imgui::Format(fmt, args));
}

void ImGui::BulletText(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_BulletText(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::BulletTextV(const char* fmt, va_list args) {
    ImGui_BulletText(Imgui::Format(fmt, args));
}

void ImGui::SeparatorText(const char* label) {
    ImGui_SeparatorText(label);
}

bool ImGui::Button(const char* label, const ImVec2& size) {
    return ImGui_Button(label, Imgui::Pack(size));
}

bool ImGui::SmallButton(const char* label) {
    return ImGui_SmallButton(label);
}

bool ImGui::InvisibleButton(const char* str_id, const ImVec2& size, ImGuiButtonFlags flags) {
    return ImGui_InvisibleButton(str_id, Imgui::Pack(size), flags);
}

bool ImGui::ArrowButton(const char* str_id, ImGuiDir dir) {
    return ImGui_ArrowButton(str_id, dir);
}

bool ImGui::Checkbox(const char* label, bool* v) {
    return ImGui_Checkbox(label, v);
}

bool ImGui::CheckboxFlags(const char* label, int* flags, int flags_value) {
    return ImGui_CheckboxFlags(label, flags, flags_value);
}

bool ImGui::CheckboxFlags(const char* label, unsigned int* flags, unsigned int flags_value) {
    return ImGui_CheckboxFlags_2(label, flags, flags_value);
}

bool ImGui::RadioButton(const char* label, bool active) {
    return ImGui_RadioButton(label, active);
}

bool ImGui::RadioButton(const char* label, int* v, int v_button) {
    return ImGui_RadioButton_2(label, v, v_button);
}

void ImGui::ProgressBar(float fraction, const ImVec2& size_arg, const char* overlay) {
    ImGui_ProgressBar(fraction, Imgui::Pack(size_arg), overlay);
}

void ImGui::Bullet() {
    ImGui_Bullet();
}

bool ImGui::TextLink(const char* label) {
    return ImGui_TextLink(label);
}

bool ImGui::TextLinkOpenURL(const char* label, const char* url) {
    return ImGui_TextLinkOpenURL(label, url);
}

void ImGui::Image(ImTextureRef tex_ref, const ImVec2& image_size, const ImVec2& uv0, const ImVec2& uv1) {
    ImGui_Image(tex_ref._TexID, Imgui::Pack(image_size), Imgui::Pack(uv0), Imgui::Pack(uv1));
}

void ImGui::ImageWithBg(ImTextureRef tex_ref, const ImVec2& image_size, const ImVec2& uv0, const ImVec2& uv1, const ImVec4& bg_col, const ImVec4& tint_col) {
    ImGui_ImageWithBg(
        tex_ref._TexID,
        Imgui::Pack(image_size),
        Imgui::Pack(uv0),
        Imgui::Pack(uv1),
        Imgui::Pack_Low(bg_col),
        Imgui::Pack_High(bg_col),
        Imgui::Pack_Low(tint_col),
        Imgui::Pack_High(tint_col)
    );
}

bool ImGui::ImageButton(
    const char* str_id,
    ImTextureRef tex_ref,
    const ImVec2& image_size,
    const ImVec2& uv0,
    const ImVec2& uv1,
    const ImVec4& bg_col,
    const ImVec4& tint_col
) {
    return ImGui_ImageButton(
        str_id,
        tex_ref._TexID,
        Imgui::Pack(image_size),
        Imgui::Pack(uv0),
        Imgui::Pack(uv1),
        Imgui::Pack_Low(bg_col),
        Imgui::Pack_High(bg_col),
        Imgui::Pack_Low(tint_col),
        Imgui::Pack_High(tint_col)
    );
}

bool ImGui::BeginCombo(const char* label, const char* preview_value, ImGuiComboFlags flags) {
    return ImGui_BeginCombo(label, preview_value, flags);
}

void ImGui::EndCombo() {
    ImGui_EndCombo();
}

bool ImGui::Combo(const char* label, int* current_item, const char* const items[], int items_count, int popup_max_height_in_items) {
    return ImGui_Combo(label, current_item, items, items_count, popup_max_height_in_items);
}

bool ImGui::Combo(const char* label, int* current_item, const char* items_separated_by_zeros, int popup_max_height_in_items) {
    return ImGui_Combo_2(label, current_item, items_separated_by_zeros, popup_max_height_in_items);
}

bool ImGui::DragFloat(const char* label, float* v, float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragFloat(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragFloat2(const char* label, float v[2], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragFloat2(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragFloat3(const char* label, float v[3], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragFloat3(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragFloat4(const char* label, float v[4], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragFloat4(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragFloatRange2(
    const char* label,
    float* v_current_min,
    float* v_current_max,
    float v_speed,
    float v_min,
    float v_max,
    const char* format,
    const char* format_max,
    ImGuiSliderFlags flags
) {
    return ImGui_DragFloatRange2(label, v_current_min, v_current_max, v_speed, v_min, v_max, format, format_max, flags);
}

bool ImGui::DragInt(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragInt(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragInt2(const char* label, int v[2], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragInt2(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragInt3(const char* label, int v[3], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragInt3(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragInt4(const char* label, int v[4], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_DragInt4(label, v, v_speed, v_min, v_max, format, flags);
}

bool ImGui::DragIntRange2(
    const char* label,
    int* v_current_min,
    int* v_current_max,
    float v_speed,
    int v_min,
    int v_max,
    const char* format,
    const char* format_max,
    ImGuiSliderFlags flags
) {
    return ImGui_DragIntRange2(label, v_current_min, v_current_max, v_speed, v_min, v_max, format, format_max, flags);
}

bool ImGui::DragScalar(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    float v_speed,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
) {
    return ImGui_DragScalar(label, data_type, p_data, v_speed, p_min, p_max, format, flags);
}

bool ImGui::DragScalarN(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    int components,
    float v_speed,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
) {
    return ImGui_DragScalarN(label, data_type, p_data, components, v_speed, p_min, p_max, format, flags);
}

bool ImGui::SliderFloat(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderFloat(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderFloat2(const char* label, float v[2], float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderFloat2(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderFloat3(const char* label, float v[3], float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderFloat3(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderFloat4(const char* label, float v[4], float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderFloat4(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderAngle(const char* label, float* v_rad, float v_degrees_min, float v_degrees_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderAngle(label, v_rad, v_degrees_min, v_degrees_max, format, flags);
}

bool ImGui::SliderInt(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderInt(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderInt2(const char* label, int v[2], int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderInt2(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderInt3(const char* label, int v[3], int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderInt3(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderInt4(const char* label, int v[4], int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_SliderInt4(label, v, v_min, v_max, format, flags);
}

bool ImGui::SliderScalar(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
) {
    return ImGui_SliderScalar(label, data_type, p_data, p_min, p_max, format, flags);
}

bool ImGui::SliderScalarN(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    int components,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
) {
    return ImGui_SliderScalarN(label, data_type, p_data, components, p_min, p_max, format, flags);
}

bool ImGui::VSliderFloat(const char* label, const ImVec2& size, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_VSliderFloat(label, Imgui::Pack(size), v, v_min, v_max, format, flags);
}

bool ImGui::VSliderInt(const char* label, const ImVec2& size, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
    return ImGui_VSliderInt(label, Imgui::Pack(size), v, v_min, v_max, format, flags);
}

bool ImGui::VSliderScalar(
    const char* label,
    const ImVec2& size,
    ImGuiDataType data_type,
    void* p_data,
    const void* p_min,
    const void* p_max,
    const char* format,
    ImGuiSliderFlags flags
) {
    return ImGui_VSliderScalar(label, Imgui::Pack(size), data_type, p_data, p_min, p_max, format, flags);
}

bool ImGui::InputText(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback, void*) {
    return ImGui_InputText(label, buf, buf_size, flags);
}

bool ImGui::InputTextMultiline(const char* label, char* buf, size_t buf_size, const ImVec2& size, ImGuiInputTextFlags flags, ImGuiInputTextCallback, void*) {
    return ImGui_InputTextMultiline(label, buf, buf_size, Imgui::Pack(size), flags);
}

bool ImGui::InputTextWithHint(const char* label, const char* hint, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback, void*) {
    return ImGui_InputTextWithHint(label, hint, buf, buf_size, flags);
}

bool ImGui::InputFloat(const char* label, float* v, float step, float step_fast, const char* format, ImGuiInputTextFlags flags) {
    return ImGui_InputFloat(label, v, step, step_fast, format, flags);
}

bool ImGui::InputFloat2(const char* label, float v[2], const char* format, ImGuiInputTextFlags flags) {
    return ImGui_InputFloat2(label, v, format, flags);
}

bool ImGui::InputFloat3(const char* label, float v[3], const char* format, ImGuiInputTextFlags flags) {
    return ImGui_InputFloat3(label, v, format, flags);
}

bool ImGui::InputFloat4(const char* label, float v[4], const char* format, ImGuiInputTextFlags flags) {
    return ImGui_InputFloat4(label, v, format, flags);
}

bool ImGui::InputInt(const char* label, int* v, int step, int step_fast, ImGuiInputTextFlags flags) {
    return ImGui_InputInt(label, v, step, step_fast, flags);
}

bool ImGui::InputInt2(const char* label, int v[2], ImGuiInputTextFlags flags) {
    return ImGui_InputInt2(label, v, flags);
}

bool ImGui::InputInt3(const char* label, int v[3], ImGuiInputTextFlags flags) {
    return ImGui_InputInt3(label, v, flags);
}

bool ImGui::InputInt4(const char* label, int v[4], ImGuiInputTextFlags flags) {
    return ImGui_InputInt4(label, v, flags);
}

bool ImGui::InputDouble(const char* label, double* v, double step, double step_fast, const char* format, ImGuiInputTextFlags flags) {
    return ImGui_InputDouble(label, v, step, step_fast, format, flags);
}

bool ImGui::InputScalar(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    const void* p_step,
    const void* p_step_fast,
    const char* format,
    ImGuiInputTextFlags flags
) {
    return ImGui_InputScalar(label, data_type, p_data, p_step, p_step_fast, format, flags);
}

bool ImGui::InputScalarN(
    const char* label,
    ImGuiDataType data_type,
    void* p_data,
    int components,
    const void* p_step,
    const void* p_step_fast,
    const char* format,
    ImGuiInputTextFlags flags
) {
    return ImGui_InputScalarN(label, data_type, p_data, components, p_step, p_step_fast, format, flags);
}

bool ImGui::ColorEdit3(const char* label, float col[3], ImGuiColorEditFlags flags) {
    return ImGui_ColorEdit3(label, col, flags);
}

bool ImGui::ColorEdit4(const char* label, float col[4], ImGuiColorEditFlags flags) {
    return ImGui_ColorEdit4(label, col, flags);
}

bool ImGui::ColorPicker3(const char* label, float col[3], ImGuiColorEditFlags flags) {
    return ImGui_ColorPicker3(label, col, flags);
}

bool ImGui::ColorPicker4(const char* label, float col[4], ImGuiColorEditFlags flags, const float* ref_col) {
    return ImGui_ColorPicker4(label, col, flags, ref_col);
}

bool ImGui::ColorButton(const char* desc_id, const ImVec4& col, ImGuiColorEditFlags flags, const ImVec2& size) {
    return ImGui_ColorButton(desc_id, Imgui::Pack_Low(col), Imgui::Pack_High(col), flags, Imgui::Pack(size));
}

bool ImGui::TreeNode(const char* label) {
    return ImGui_TreeNode(label);
}

bool ImGui::TreeNode(const char* str_id, const char* fmt, ...) {
    va_list arguments;
    bool result;

    va_start(arguments, fmt);
    result = ImGui_TreeNode_2(str_id, Imgui::Format(fmt, arguments));
    va_end(arguments);
    return result;
}

bool ImGui::TreeNode(const void* ptr_id, const char* fmt, ...) {
    va_list arguments;
    bool result;

    va_start(arguments, fmt);
    result = ImGui_TreeNode_3(ptr_id, Imgui::Format(fmt, arguments));
    va_end(arguments);
    return result;
}

bool ImGui::TreeNodeV(const char* str_id, const char* fmt, va_list args) {
    return ImGui_TreeNode_2(str_id, Imgui::Format(fmt, args));
}

bool ImGui::TreeNodeV(const void* ptr_id, const char* fmt, va_list args) {
    return ImGui_TreeNode_3(ptr_id, Imgui::Format(fmt, args));
}

bool ImGui::TreeNodeEx(const char* label, ImGuiTreeNodeFlags flags) {
    return ImGui_TreeNodeEx(label, flags);
}

bool ImGui::TreeNodeEx(const char* str_id, ImGuiTreeNodeFlags flags, const char* fmt, ...) {
    va_list arguments;
    bool result;

    va_start(arguments, fmt);
    result = ImGui_TreeNodeEx_2(str_id, flags, Imgui::Format(fmt, arguments));
    va_end(arguments);
    return result;
}

bool ImGui::TreeNodeEx(const void* ptr_id, ImGuiTreeNodeFlags flags, const char* fmt, ...) {
    va_list arguments;
    bool result;

    va_start(arguments, fmt);
    result = ImGui_TreeNodeEx_3(ptr_id, flags, Imgui::Format(fmt, arguments));
    va_end(arguments);
    return result;
}

bool ImGui::TreeNodeExV(const char* str_id, ImGuiTreeNodeFlags flags, const char* fmt, va_list args) {
    return ImGui_TreeNodeEx_2(str_id, flags, Imgui::Format(fmt, args));
}

bool ImGui::TreeNodeExV(const void* ptr_id, ImGuiTreeNodeFlags flags, const char* fmt, va_list args) {
    return ImGui_TreeNodeEx_3(ptr_id, flags, Imgui::Format(fmt, args));
}

void ImGui::TreePush(const char* str_id) {
    ImGui_TreePush(str_id);
}

void ImGui::TreePush(const void* ptr_id) {
    ImGui_TreePush_2(ptr_id);
}

void ImGui::TreePop() {
    ImGui_TreePop();
}

float ImGui::GetTreeNodeToLabelSpacing() {
    return ImGui_GetTreeNodeToLabelSpacing();
}

bool ImGui::CollapsingHeader(const char* label, ImGuiTreeNodeFlags flags) {
    return ImGui_CollapsingHeader(label, flags);
}

bool ImGui::CollapsingHeader(const char* label, bool* p_visible, ImGuiTreeNodeFlags flags) {
    return ImGui_CollapsingHeader_2(label, p_visible, flags);
}

void ImGui::SetNextItemOpen(bool is_open, ImGuiCond cond) {
    ImGui_SetNextItemOpen(is_open, cond);
}

void ImGui::SetNextItemStorageID(ImGuiID storage_id) {
    ImGui_SetNextItemStorageID(storage_id);
}

bool ImGui::TreeNodeGetOpen(ImGuiID storage_id) {
    return ImGui_TreeNodeGetOpen(storage_id);
}

bool ImGui::Selectable(const char* label, bool selected, ImGuiSelectableFlags flags, const ImVec2& size) {
    return ImGui_Selectable(label, selected, flags, Imgui::Pack(size));
}

bool ImGui::Selectable(const char* label, bool* p_selected, ImGuiSelectableFlags flags, const ImVec2& size) {
    return ImGui_Selectable_2(label, p_selected, flags, Imgui::Pack(size));
}

void ImGui::SetNextItemSelectionUserData(ImGuiSelectionUserData selection_user_data) {
    ImGui_SetNextItemSelectionUserData(selection_user_data);
}

bool ImGui::IsItemToggledSelection() {
    return ImGui_IsItemToggledSelection();
}

bool ImGui::BeginListBox(const char* label, const ImVec2& size) {
    return ImGui_BeginListBox(label, Imgui::Pack(size));
}

void ImGui::EndListBox() {
    ImGui_EndListBox();
}

bool ImGui::ListBox(const char* label, int* current_item, const char* const items[], int items_count, int height_in_items) {
    return ImGui_ListBox(label, current_item, items, items_count, height_in_items);
}

void ImGui::PlotLines(
    const char* label,
    const float* values,
    int values_count,
    int values_offset,
    const char* overlay_text,
    float scale_min,
    float scale_max,
    ImVec2 graph_size,
    int stride
) {
    ImGui_PlotLines(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, Imgui::Pack(graph_size), stride);
}

void ImGui::PlotHistogram(
    const char* label,
    const float* values,
    int values_count,
    int values_offset,
    const char* overlay_text,
    float scale_min,
    float scale_max,
    ImVec2 graph_size,
    int stride
) {
    ImGui_PlotHistogram(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, Imgui::Pack(graph_size), stride);
}

void ImGui::Value(const char* prefix, bool b) {
    ImGui_Value(prefix, b);
}

void ImGui::Value(const char* prefix, int v) {
    ImGui_Value_2(prefix, v);
}

void ImGui::Value(const char* prefix, unsigned int v) {
    ImGui_Value_3(prefix, v);
}

void ImGui::Value(const char* prefix, float v, const char* float_format) {
    ImGui_Value_4(prefix, v, float_format);
}

bool ImGui::BeginMenuBar() {
    return ImGui_BeginMenuBar();
}

void ImGui::EndMenuBar() {
    ImGui_EndMenuBar();
}

bool ImGui::BeginMainMenuBar() {
    return ImGui_BeginMainMenuBar();
}

void ImGui::EndMainMenuBar() {
    ImGui_EndMainMenuBar();
}

bool ImGui::BeginMenu(const char* label, bool enabled) {
    return ImGui_BeginMenu(label, enabled);
}

void ImGui::EndMenu() {
    ImGui_EndMenu();
}

bool ImGui::MenuItem(const char* label, const char* shortcut, bool selected, bool enabled) {
    return ImGui_MenuItem(label, shortcut, selected, enabled);
}

bool ImGui::MenuItem(const char* label, const char* shortcut, bool* p_selected, bool enabled) {
    return ImGui_MenuItem_2(label, shortcut, p_selected, enabled);
}

bool ImGui::BeginTooltip() {
    return ImGui_BeginTooltip();
}

void ImGui::EndTooltip() {
    ImGui_EndTooltip();
}

void ImGui::SetTooltip(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_SetTooltip(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::SetTooltipV(const char* fmt, va_list args) {
    ImGui_SetTooltip(Imgui::Format(fmt, args));
}

bool ImGui::BeginItemTooltip() {
    return ImGui_BeginItemTooltip();
}

void ImGui::SetItemTooltip(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_SetItemTooltip(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::SetItemTooltipV(const char* fmt, va_list args) {
    ImGui_SetItemTooltip(Imgui::Format(fmt, args));
}

bool ImGui::BeginPopup(const char* str_id, ImGuiWindowFlags flags) {
    return ImGui_BeginPopup(str_id, flags);
}

bool ImGui::BeginPopupModal(const char* name, bool* p_open, ImGuiWindowFlags flags) {
    return ImGui_BeginPopupModal(name, p_open, flags);
}

void ImGui::EndPopup() {
    ImGui_EndPopup();
}

bool ImGui::OpenPopup(const char* str_id, ImGuiPopupFlags popup_flags) {
    return ImGui_OpenPopup(str_id, popup_flags);
}

bool ImGui::OpenPopup(ImGuiID id, ImGuiPopupFlags popup_flags) {
    return ImGui_OpenPopup_2(id, popup_flags);
}

bool ImGui::OpenPopupOnItemClick(const char* str_id, ImGuiPopupFlags popup_flags) {
    return ImGui_OpenPopupOnItemClick(str_id, popup_flags);
}

void ImGui::CloseCurrentPopup() {
    ImGui_CloseCurrentPopup();
}

bool ImGui::BeginPopupContextItem(const char* str_id, ImGuiPopupFlags popup_flags) {
    return ImGui_BeginPopupContextItem(str_id, popup_flags);
}

bool ImGui::BeginPopupContextWindow(const char* str_id, ImGuiPopupFlags popup_flags) {
    return ImGui_BeginPopupContextWindow(str_id, popup_flags);
}

bool ImGui::BeginPopupContextVoid(const char* str_id, ImGuiPopupFlags popup_flags) {
    return ImGui_BeginPopupContextVoid(str_id, popup_flags);
}

bool ImGui::IsPopupOpen(const char* str_id, ImGuiPopupFlags flags) {
    return ImGui_IsPopupOpen(str_id, flags);
}

bool ImGui::BeginTable(const char* str_id, int columns, ImGuiTableFlags flags, const ImVec2& outer_size, float inner_width) {
    return ImGui_BeginTable(str_id, columns, flags, Imgui::Pack(outer_size), inner_width);
}

void ImGui::EndTable() {
    ImGui_EndTable();
}

void ImGui::TableNextRow(ImGuiTableRowFlags row_flags, float min_row_height) {
    ImGui_TableNextRow(row_flags, min_row_height);
}

bool ImGui::TableNextColumn() {
    return ImGui_TableNextColumn();
}

bool ImGui::TableSetColumnIndex(int column_n) {
    return ImGui_TableSetColumnIndex(column_n);
}

void ImGui::TableSetupColumn(const char* label, ImGuiTableColumnFlags flags, float init_width_or_weight, ImGuiID user_data) {
    ImGui_TableSetupColumn(label, flags, init_width_or_weight, user_data);
}

void ImGui::TableSetupScrollFreeze(int cols, int rows) {
    ImGui_TableSetupScrollFreeze(cols, rows);
}

void ImGui::TableHeader(const char* label) {
    ImGui_TableHeader(label);
}

void ImGui::TableHeadersRow() {
    ImGui_TableHeadersRow();
}

void ImGui::TableAngledHeadersRow() {
    ImGui_TableAngledHeadersRow();
}

int ImGui::TableGetColumnCount() {
    return ImGui_TableGetColumnCount();
}

int ImGui::TableGetColumnIndex() {
    return ImGui_TableGetColumnIndex();
}

int ImGui::TableGetRowIndex() {
    return ImGui_TableGetRowIndex();
}

const char* ImGui::TableGetColumnName(int column_n) {
    u64 capacity = 256;
    char* buffer = Imgui::Scratch_Text(capacity);
    u64 length = ImGui_TableGetColumnName(column_n, buffer, capacity);

    if (length >= capacity) {
        capacity = length + 1;
        buffer = Imgui::Scratch_Text(capacity);
        ImGui_TableGetColumnName(column_n, buffer, capacity);
    }
    return buffer;
}

ImGuiTableColumnFlags ImGui::TableGetColumnFlags(int column_n) {
    return ImGui_TableGetColumnFlags(column_n);
}

void ImGui::TableSetColumnEnabled(int column_n, bool v) {
    ImGui_TableSetColumnEnabled(column_n, v);
}

int ImGui::TableGetHoveredColumn() {
    return ImGui_TableGetHoveredColumn();
}

void ImGui::TableSetBgColor(ImGuiTableBgTarget target, ImU32 color, int column_n) {
    ImGui_TableSetBgColor(target, color, column_n);
}

void ImGui::Columns(int count, const char* id, bool borders) {
    ImGui_Columns(count, id, borders);
}

void ImGui::NextColumn() {
    ImGui_NextColumn();
}

int ImGui::GetColumnIndex() {
    return ImGui_GetColumnIndex();
}

float ImGui::GetColumnWidth(int column_index) {
    return ImGui_GetColumnWidth(column_index);
}

void ImGui::SetColumnWidth(int column_index, float width) {
    ImGui_SetColumnWidth(column_index, width);
}

float ImGui::GetColumnOffset(int column_index) {
    return ImGui_GetColumnOffset(column_index);
}

void ImGui::SetColumnOffset(int column_index, float offset_x) {
    ImGui_SetColumnOffset(column_index, offset_x);
}

int ImGui::GetColumnsCount() {
    return ImGui_GetColumnsCount();
}

bool ImGui::BeginTabBar(const char* str_id, ImGuiTabBarFlags flags) {
    return ImGui_BeginTabBar(str_id, flags);
}

void ImGui::EndTabBar() {
    ImGui_EndTabBar();
}

bool ImGui::BeginTabItem(const char* label, bool* p_open, ImGuiTabItemFlags flags) {
    return ImGui_BeginTabItem(label, p_open, flags);
}

void ImGui::EndTabItem() {
    ImGui_EndTabItem();
}

bool ImGui::TabItemButton(const char* label, ImGuiTabItemFlags flags) {
    return ImGui_TabItemButton(label, flags);
}

void ImGui::SetTabItemClosed(const char* tab_or_docked_window_label) {
    ImGui_SetTabItemClosed(tab_or_docked_window_label);
}

ImGuiID ImGui::DockSpace(ImGuiID dockspace_id, const ImVec2& size, ImGuiDockNodeFlags flags, const ImGuiWindowClass* window_class) {
    return ImGui_DockSpace(dockspace_id, Imgui::Pack(size), flags, window_class);
}

ImGuiID ImGui::DockSpaceOverViewport(ImGuiID dockspace_id, const ImGuiViewport* viewport, ImGuiDockNodeFlags flags, const ImGuiWindowClass* window_class) {
    return ImGui_DockSpaceOverViewport(dockspace_id, Imgui::Viewport_Id(viewport), flags, window_class);
}

void ImGui::SetNextWindowDockID(ImGuiID dock_id, ImGuiCond cond) {
    ImGui_SetNextWindowDockID(dock_id, cond);
}

void ImGui::SetNextWindowClass(const ImGuiWindowClass* window_class) {
    ImGui_SetNextWindowClass(window_class);
}

ImGuiID ImGui::GetWindowDockID() {
    return ImGui_GetWindowDockID();
}

bool ImGui::IsWindowDocked() {
    return ImGui_IsWindowDocked();
}

void ImGui::LogToTTY(int auto_open_depth) {
    ImGui_LogToTTY(auto_open_depth);
}

void ImGui::LogToClipboard(int auto_open_depth) {
    ImGui_LogToClipboard(auto_open_depth);
}

void ImGui::LogFinish() {
    ImGui_LogFinish();
}

void ImGui::LogText(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_LogText(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::LogTextV(const char* fmt, va_list args) {
    ImGui_LogText(Imgui::Format(fmt, args));
}

bool ImGui::BeginDragDropSource(ImGuiDragDropFlags flags) {
    return ImGui_BeginDragDropSource(flags);
}

bool ImGui::SetDragDropPayload(const char* type, const void* data, size_t sz, ImGuiCond cond) {
    return ImGui_SetDragDropPayload(type, data, sz, cond);
}

void ImGui::EndDragDropSource() {
    ImGui_EndDragDropSource();
}

bool ImGui::BeginDragDropTarget() {
    return ImGui_BeginDragDropTarget();
}

void ImGui::EndDragDropTarget() {
    ImGui_EndDragDropTarget();
}

void ImGui::BeginDisabled(bool disabled) {
    ImGui_BeginDisabled(disabled);
}

void ImGui::EndDisabled() {
    ImGui_EndDisabled();
}

void ImGui::PushClipRect(const ImVec2& clip_rect_min, const ImVec2& clip_rect_max, bool intersect_with_current_clip_rect) {
    ImGui_PushClipRect(Imgui::Pack(clip_rect_min), Imgui::Pack(clip_rect_max), intersect_with_current_clip_rect);
}

void ImGui::PopClipRect() {
    ImGui_PopClipRect();
}

void ImGui::SetItemDefaultFocus() {
    ImGui_SetItemDefaultFocus();
}

void ImGui::SetKeyboardFocusHere(int offset) {
    ImGui_SetKeyboardFocusHere(offset);
}

void ImGui::SetNavCursorVisible(bool visible) {
    ImGui_SetNavCursorVisible(visible);
}

void ImGui::SetNextItemAllowOverlap() {
    ImGui_SetNextItemAllowOverlap();
}

bool ImGui::IsItemHovered(ImGuiHoveredFlags flags) {
    return ImGui_IsItemHovered(flags);
}

bool ImGui::IsItemActive() {
    return ImGui_IsItemActive();
}

bool ImGui::IsItemFocused() {
    return ImGui_IsItemFocused();
}

bool ImGui::IsItemClicked(ImGuiMouseButton mouse_button) {
    return ImGui_IsItemClicked(mouse_button);
}

bool ImGui::IsItemVisible() {
    return ImGui_IsItemVisible();
}

bool ImGui::IsItemEdited() {
    return ImGui_IsItemEdited();
}

bool ImGui::IsItemActivated() {
    return ImGui_IsItemActivated();
}

bool ImGui::IsItemDeactivated() {
    return ImGui_IsItemDeactivated();
}

bool ImGui::IsItemDeactivatedAfterEdit() {
    return ImGui_IsItemDeactivatedAfterEdit();
}

bool ImGui::IsItemToggledOpen() {
    return ImGui_IsItemToggledOpen();
}

bool ImGui::IsAnyItemHovered() {
    return ImGui_IsAnyItemHovered();
}

bool ImGui::IsAnyItemActive() {
    return ImGui_IsAnyItemActive();
}

bool ImGui::IsAnyItemFocused() {
    return ImGui_IsAnyItemFocused();
}

ImGuiID ImGui::GetItemID() {
    return ImGui_GetItemID();
}

ImVec2 ImGui::GetItemRectMin() {
    return Imgui::Unpack(ImGui_GetItemRectMin());
}

ImVec2 ImGui::GetItemRectMax() {
    return Imgui::Unpack(ImGui_GetItemRectMax());
}

ImVec2 ImGui::GetItemRectSize() {
    return Imgui::Unpack(ImGui_GetItemRectSize());
}

ImGuiItemFlags ImGui::GetItemFlags() {
    return ImGui_GetItemFlags();
}

int ImGui::GetItemClickedCountWithSingleClickDelay(ImGuiMouseButton mouse_button, float delay) {
    return ImGui_GetItemClickedCountWithSingleClickDelay(mouse_button, delay);
}

ImGuiViewport* ImGui::GetMainViewport() {
    return Imgui::Viewport(ImGui_GetMainViewport());
}

ImDrawList* ImGui::GetBackgroundDrawList(ImGuiViewport* viewport) {
    return Imgui::Draw_List(ImGui_GetBackgroundDrawList(Imgui::Viewport_Id(viewport)));
}

ImDrawList* ImGui::GetForegroundDrawList(ImGuiViewport* viewport) {
    return Imgui::Draw_List(ImGui_GetForegroundDrawList(Imgui::Viewport_Id(viewport)));
}

bool ImGui::IsRectVisible(const ImVec2& size) {
    return ImGui_IsRectVisible(Imgui::Pack(size));
}

bool ImGui::IsRectVisible(const ImVec2& rect_min, const ImVec2& rect_max) {
    return ImGui_IsRectVisible_2(Imgui::Pack(rect_min), Imgui::Pack(rect_max));
}

double ImGui::GetTime() {
    return ImGui_GetTime();
}

int ImGui::GetFrameCount() {
    return ImGui_GetFrameCount();
}

const char* ImGui::GetStyleColorName(ImGuiCol idx) {
    u64 capacity = 256;
    char* buffer = Imgui::Scratch_Text(capacity);
    u64 length = ImGui_GetStyleColorName(idx, buffer, capacity);

    if (length >= capacity) {
        capacity = length + 1;
        buffer = Imgui::Scratch_Text(capacity);
        ImGui_GetStyleColorName(idx, buffer, capacity);
    }
    return buffer;
}

ImVec2 ImGui::CalcTextSize(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width) {
    return Imgui::Unpack(ImGui_CalcTextSize(text, text_end, hide_text_after_double_hash, wrap_width));
}

ImVec4 ImGui::ColorConvertU32ToFloat4(ImU32 in) {
    ImVec4 result;

    ImGui_ColorConvertU32ToFloat4(in, &result);
    return result;
}

ImU32 ImGui::ColorConvertFloat4ToU32(const ImVec4& in) {
    return ImGui_ColorConvertFloat4ToU32(Imgui::Pack_Low(in), Imgui::Pack_High(in));
}

void ImGui::ColorConvertRGBtoHSV(float r, float g, float b, float& out_h, float& out_s, float& out_v) {
    ImGui_ColorConvertRGBtoHSV(r, g, b, &out_h, &out_s, &out_v);
}

void ImGui::ColorConvertHSVtoRGB(float h, float s, float v, float& out_r, float& out_g, float& out_b) {
    ImGui_ColorConvertHSVtoRGB(h, s, v, &out_r, &out_g, &out_b);
}

bool ImGui::IsKeyDown(ImGuiKey key) {
    return ImGui_IsKeyDown(key);
}

bool ImGui::IsKeyPressed(ImGuiKey key, bool repeat) {
    return ImGui_IsKeyPressed(key, repeat);
}

bool ImGui::IsKeyReleased(ImGuiKey key) {
    return ImGui_IsKeyReleased(key);
}

bool ImGui::IsKeyChordPressed(ImGuiKeyChord key_chord) {
    return ImGui_IsKeyChordPressed(key_chord);
}

int ImGui::GetKeyPressedAmount(ImGuiKey key, float repeat_delay, float rate) {
    return ImGui_GetKeyPressedAmount(key, repeat_delay, rate);
}

const char* ImGui::GetKeyName(ImGuiKey key) {
    u64 capacity = 256;
    char* buffer = Imgui::Scratch_Text(capacity);
    u64 length = ImGui_GetKeyName(key, buffer, capacity);

    if (length >= capacity) {
        capacity = length + 1;
        buffer = Imgui::Scratch_Text(capacity);
        ImGui_GetKeyName(key, buffer, capacity);
    }
    return buffer;
}

void ImGui::SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard) {
    ImGui_SetNextFrameWantCaptureKeyboard(want_capture_keyboard);
}

bool ImGui::Shortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags) {
    return ImGui_Shortcut(key_chord, flags);
}

void ImGui::SetNextItemShortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags) {
    ImGui_SetNextItemShortcut(key_chord, flags);
}

bool ImGui::SetItemKeyOwner(ImGuiKey key) {
    return ImGui_SetItemKeyOwner(key);
}

bool ImGui::IsMouseDown(ImGuiMouseButton button) {
    return ImGui_IsMouseDown(button);
}

bool ImGui::IsMouseClicked(ImGuiMouseButton button, bool repeat) {
    return ImGui_IsMouseClicked(button, repeat);
}

bool ImGui::IsMouseReleased(ImGuiMouseButton button) {
    return ImGui_IsMouseReleased(button);
}

bool ImGui::IsMouseDoubleClicked(ImGuiMouseButton button) {
    return ImGui_IsMouseDoubleClicked(button);
}

bool ImGui::IsMouseReleasedWithDelay(ImGuiMouseButton button, float delay) {
    return ImGui_IsMouseReleasedWithDelay(button, delay);
}

int ImGui::GetMouseClickedCount(ImGuiMouseButton button) {
    return ImGui_GetMouseClickedCount(button);
}

bool ImGui::IsMouseHoveringRect(const ImVec2& r_min, const ImVec2& r_max, bool clip) {
    return ImGui_IsMouseHoveringRect(Imgui::Pack(r_min), Imgui::Pack(r_max), clip);
}

bool ImGui::IsMousePosValid(const ImVec2* mouse_pos) {
    return ImGui_IsMousePosValid(mouse_pos);
}

bool ImGui::IsAnyMouseDown() {
    return ImGui_IsAnyMouseDown();
}

ImVec2 ImGui::GetMousePos() {
    return Imgui::Unpack(ImGui_GetMousePos());
}

ImVec2 ImGui::GetMousePosOnOpeningCurrentPopup() {
    return Imgui::Unpack(ImGui_GetMousePosOnOpeningCurrentPopup());
}

bool ImGui::IsMouseDragging(ImGuiMouseButton button, float lock_threshold) {
    return ImGui_IsMouseDragging(button, lock_threshold);
}

ImVec2 ImGui::GetMouseDragDelta(ImGuiMouseButton button, float lock_threshold) {
    return Imgui::Unpack(ImGui_GetMouseDragDelta(button, lock_threshold));
}

void ImGui::ResetMouseDragDelta(ImGuiMouseButton button) {
    ImGui_ResetMouseDragDelta(button);
}

ImGuiMouseCursor ImGui::GetMouseCursor() {
    return ImGui_GetMouseCursor();
}

void ImGui::SetMouseCursor(ImGuiMouseCursor cursor_type) {
    ImGui_SetMouseCursor(cursor_type);
}

void ImGui::SetNextFrameWantCaptureMouse(bool want_capture_mouse) {
    ImGui_SetNextFrameWantCaptureMouse(want_capture_mouse);
}

const char* ImGui::GetClipboardText() {
    u64 capacity = 256;
    char* buffer = Imgui::Scratch_Text(capacity);
    u64 length = ImGui_GetClipboardText(buffer, capacity);

    if (length >= capacity) {
        capacity = length + 1;
        buffer = Imgui::Scratch_Text(capacity);
        ImGui_GetClipboardText(buffer, capacity);
    }
    return buffer;
}

void ImGui::SetClipboardText(const char* text) {
    ImGui_SetClipboardText(text);
}

void ImGui::DebugTextEncoding(const char* text) {
    ImGui_DebugTextEncoding(text);
}

void ImGui::DebugFlashStyleColor(ImGuiCol idx) {
    ImGui_DebugFlashStyleColor(idx);
}

void ImGui::DebugStartItemPicker() {
    ImGui_DebugStartItemPicker();
}

void ImGui::DebugLog(const char* fmt, ...) {
    va_list arguments;

    va_start(arguments, fmt);
    ImGui_DebugLog(Imgui::Format(fmt, arguments));
    va_end(arguments);
}

void ImGui::DebugLogV(const char* fmt, va_list args) {
    ImGui_DebugLog(Imgui::Format(fmt, args));
}

ImGuiViewport* ImGui::FindViewportByID(ImGuiID viewport_id) {
    return Imgui::Viewport(ImGui_FindViewportByID(viewport_id));
}

void ImDrawList::PushClipRect(const ImVec2& clip_rect_min, const ImVec2& clip_rect_max, bool intersect_with_current_clip_rect) {
    ImDrawList_PushClipRect(Imgui::Draw_List_Handle(this), Imgui::Pack(clip_rect_min), Imgui::Pack(clip_rect_max), intersect_with_current_clip_rect);
}

void ImDrawList::PushClipRectFullScreen() {
    ImDrawList_PushClipRectFullScreen(Imgui::Draw_List_Handle(this));
}

void ImDrawList::PopClipRect() {
    ImDrawList_PopClipRect(Imgui::Draw_List_Handle(this));
}

void ImDrawList::PushTexture(ImTextureRef tex_ref) {
    ImDrawList_PushTexture(Imgui::Draw_List_Handle(this), tex_ref._TexID);
}

void ImDrawList::PopTexture() {
    ImDrawList_PopTexture(Imgui::Draw_List_Handle(this));
}

void ImDrawList::AddLine(const ImVec2& p1, const ImVec2& p2, ImU32 col, float thickness) {
    ImDrawList_AddLine(Imgui::Draw_List_Handle(this), Imgui::Pack(p1), Imgui::Pack(p2), col, thickness);
}

void ImDrawList::AddLineH(float min_x, float max_x, float y, ImU32 col, float thickness) {
    ImDrawList_AddLineH(Imgui::Draw_List_Handle(this), min_x, max_x, y, col, thickness);
}

void ImDrawList::AddLineV(float x, float min_y, float max_y, ImU32 col, float thickness) {
    ImDrawList_AddLineV(Imgui::Draw_List_Handle(this), x, min_y, max_y, col, thickness);
}

void ImDrawList::AddRect(const ImVec2& p_min, const ImVec2& p_max, ImU32 col, float rounding, float thickness, ImDrawFlags flags) {
    ImDrawList_AddRect(Imgui::Draw_List_Handle(this), Imgui::Pack(p_min), Imgui::Pack(p_max), col, rounding, thickness, flags);
}

void ImDrawList::AddRectFilled(const ImVec2& p_min, const ImVec2& p_max, ImU32 col, float rounding, ImDrawFlags flags) {
    ImDrawList_AddRectFilled(Imgui::Draw_List_Handle(this), Imgui::Pack(p_min), Imgui::Pack(p_max), col, rounding, flags);
}

void ImDrawList::AddRectFilledMultiColor(
    const ImVec2& p_min,
    const ImVec2& p_max,
    ImU32 col_upr_left,
    ImU32 col_upr_right,
    ImU32 col_bot_right,
    ImU32 col_bot_left
) {
    ImDrawList_AddRectFilledMultiColor(
        Imgui::Draw_List_Handle(this),
        Imgui::Pack(p_min),
        Imgui::Pack(p_max),
        col_upr_left,
        col_upr_right,
        col_bot_right,
        col_bot_left
    );
}

void ImDrawList::AddQuad(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, const ImVec2& p4, ImU32 col, float thickness) {
    ImDrawList_AddQuad(Imgui::Draw_List_Handle(this), Imgui::Pack(p1), Imgui::Pack(p2), Imgui::Pack(p3), Imgui::Pack(p4), col, thickness);
}

void ImDrawList::AddQuadFilled(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, const ImVec2& p4, ImU32 col) {
    ImDrawList_AddQuadFilled(Imgui::Draw_List_Handle(this), Imgui::Pack(p1), Imgui::Pack(p2), Imgui::Pack(p3), Imgui::Pack(p4), col);
}

void ImDrawList::AddTriangle(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, ImU32 col, float thickness) {
    ImDrawList_AddTriangle(Imgui::Draw_List_Handle(this), Imgui::Pack(p1), Imgui::Pack(p2), Imgui::Pack(p3), col, thickness);
}

void ImDrawList::AddTriangleFilled(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, ImU32 col) {
    ImDrawList_AddTriangleFilled(Imgui::Draw_List_Handle(this), Imgui::Pack(p1), Imgui::Pack(p2), Imgui::Pack(p3), col);
}

void ImDrawList::AddCircle(const ImVec2& center, float radius, ImU32 col, int num_segments, float thickness) {
    ImDrawList_AddCircle(Imgui::Draw_List_Handle(this), Imgui::Pack(center), radius, col, num_segments, thickness);
}

void ImDrawList::AddCircleFilled(const ImVec2& center, float radius, ImU32 col, int num_segments) {
    ImDrawList_AddCircleFilled(Imgui::Draw_List_Handle(this), Imgui::Pack(center), radius, col, num_segments);
}

void ImDrawList::AddNgon(const ImVec2& center, float radius, ImU32 col, int num_segments, float thickness) {
    ImDrawList_AddNgon(Imgui::Draw_List_Handle(this), Imgui::Pack(center), radius, col, num_segments, thickness);
}

void ImDrawList::AddNgonFilled(const ImVec2& center, float radius, ImU32 col, int num_segments) {
    ImDrawList_AddNgonFilled(Imgui::Draw_List_Handle(this), Imgui::Pack(center), radius, col, num_segments);
}

void ImDrawList::AddEllipse(const ImVec2& center, const ImVec2& radius, ImU32 col, float rot, int num_segments, float thickness) {
    ImDrawList_AddEllipse(Imgui::Draw_List_Handle(this), Imgui::Pack(center), Imgui::Pack(radius), col, rot, num_segments, thickness);
}

void ImDrawList::AddEllipseFilled(const ImVec2& center, const ImVec2& radius, ImU32 col, float rot, int num_segments) {
    ImDrawList_AddEllipseFilled(Imgui::Draw_List_Handle(this), Imgui::Pack(center), Imgui::Pack(radius), col, rot, num_segments);
}

void ImDrawList::AddText(const ImVec2& pos, ImU32 col, const char* text_begin, const char* text_end) {
    ImDrawList_AddText(Imgui::Draw_List_Handle(this), Imgui::Pack(pos), col, text_begin, text_end);
}

void ImDrawList::AddText(
    ImFont* font,
    float font_size,
    const ImVec2& pos,
    ImU32 col,
    const char* text_begin,
    const char* text_end,
    float wrap_width,
    const ImVec4* cpu_fine_clip_rect
) {
    ImDrawList_AddText_2(
        Imgui::Draw_List_Handle(this),
        Imgui::Font_Handle(font),
        font_size,
        Imgui::Pack(pos),
        col,
        text_begin,
        text_end,
        wrap_width,
        cpu_fine_clip_rect
    );
}

void ImDrawList::AddBezierCubic(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, const ImVec2& p4, ImU32 col, float thickness, int num_segments) {
    ImDrawList_AddBezierCubic(Imgui::Draw_List_Handle(this), Imgui::Pack(p1), Imgui::Pack(p2), Imgui::Pack(p3), Imgui::Pack(p4), col, thickness, num_segments);
}

void ImDrawList::AddBezierQuadratic(const ImVec2& p1, const ImVec2& p2, const ImVec2& p3, ImU32 col, float thickness, int num_segments) {
    ImDrawList_AddBezierQuadratic(Imgui::Draw_List_Handle(this), Imgui::Pack(p1), Imgui::Pack(p2), Imgui::Pack(p3), col, thickness, num_segments);
}

void ImDrawList::AddPolyline(const ImVec2* points, int num_points, ImU32 col, float thickness, ImDrawFlags flags) {
    ImDrawList_AddPolyline(Imgui::Draw_List_Handle(this), points, num_points, col, thickness, flags);
}

void ImDrawList::AddConvexPolyFilled(const ImVec2* points, int num_points, ImU32 col) {
    ImDrawList_AddConvexPolyFilled(Imgui::Draw_List_Handle(this), points, num_points, col);
}

void ImDrawList::AddConcavePolyFilled(const ImVec2* points, int num_points, ImU32 col) {
    ImDrawList_AddConcavePolyFilled(Imgui::Draw_List_Handle(this), points, num_points, col);
}

void ImDrawList::AddImage(ImTextureRef tex_ref, const ImVec2& p_min, const ImVec2& p_max, const ImVec2& uv_min, const ImVec2& uv_max, ImU32 col) {
    ImDrawList_AddImage(Imgui::Draw_List_Handle(this), tex_ref._TexID, Imgui::Pack(p_min), Imgui::Pack(p_max), Imgui::Pack(uv_min), Imgui::Pack(uv_max), col);
}

void ImDrawList::AddImageQuad(
    ImTextureRef tex_ref,
    const ImVec2& p1,
    const ImVec2& p2,
    const ImVec2& p3,
    const ImVec2& p4,
    const ImVec2& uv1,
    const ImVec2& uv2,
    const ImVec2& uv3,
    const ImVec2& uv4,
    ImU32 col
) {
    ImDrawList_AddImageQuad(
        Imgui::Draw_List_Handle(this),
        tex_ref._TexID,
        Imgui::Pack(p1),
        Imgui::Pack(p2),
        Imgui::Pack(p3),
        Imgui::Pack(p4),
        Imgui::Pack(uv1),
        Imgui::Pack(uv2),
        Imgui::Pack(uv3),
        Imgui::Pack(uv4),
        col
    );
}

void ImDrawList::AddImageRounded(
    ImTextureRef tex_ref,
    const ImVec2& p_min,
    const ImVec2& p_max,
    const ImVec2& uv_min,
    const ImVec2& uv_max,
    ImU32 col,
    float rounding,
    ImDrawFlags flags
) {
    ImDrawList_AddImageRounded(
        Imgui::Draw_List_Handle(this),
        tex_ref._TexID,
        Imgui::Pack(p_min),
        Imgui::Pack(p_max),
        Imgui::Pack(uv_min),
        Imgui::Pack(uv_max),
        col,
        rounding,
        flags
    );
}

void ImDrawList::PathArcTo(const ImVec2& center, float radius, float a_min, float a_max, int num_segments) {
    ImDrawList_PathArcTo(Imgui::Draw_List_Handle(this), Imgui::Pack(center), radius, a_min, a_max, num_segments);
}

void ImDrawList::PathArcToFast(const ImVec2& center, float radius, int a_min_of_12, int a_max_of_12) {
    ImDrawList_PathArcToFast(Imgui::Draw_List_Handle(this), Imgui::Pack(center), radius, a_min_of_12, a_max_of_12);
}

void ImDrawList::PathEllipticalArcTo(const ImVec2& center, const ImVec2& radius, float rot, float a_min, float a_max, int num_segments) {
    ImDrawList_PathEllipticalArcTo(Imgui::Draw_List_Handle(this), Imgui::Pack(center), Imgui::Pack(radius), rot, a_min, a_max, num_segments);
}

void ImDrawList::PathBezierCubicCurveTo(const ImVec2& p2, const ImVec2& p3, const ImVec2& p4, int num_segments) {
    ImDrawList_PathBezierCubicCurveTo(Imgui::Draw_List_Handle(this), Imgui::Pack(p2), Imgui::Pack(p3), Imgui::Pack(p4), num_segments);
}

void ImDrawList::PathBezierQuadraticCurveTo(const ImVec2& p2, const ImVec2& p3, int num_segments) {
    ImDrawList_PathBezierQuadraticCurveTo(Imgui::Draw_List_Handle(this), Imgui::Pack(p2), Imgui::Pack(p3), num_segments);
}

void ImDrawList::PathRect(const ImVec2& rect_min, const ImVec2& rect_max, float rounding, ImDrawFlags flags) {
    ImDrawList_PathRect(Imgui::Draw_List_Handle(this), Imgui::Pack(rect_min), Imgui::Pack(rect_max), rounding, flags);
}

void ImDrawList::AddDrawCmd() {
    ImDrawList_AddDrawCmd(Imgui::Draw_List_Handle(this));
}
